/**
 * signal-accuracy.ts
 *
 * Karpathy AutoResearch Loop for Capital Flows + F&G
 * 1W/4W/13W 3개 타임프레임 모두 적용
 *
 * Editable asset : 로테이션 신호 (from→to, spread%)
 * Scalar metric  : 신호 발생 N주 후 실제 수익률 방향 일치율
 * Loop           : 신호 저장 → 주기적 평가 → 임계값 자동 조정
 *
 * Redis keys:
 *  flowvium:signal:log:v1          — 신호 기록 (LPUSH, max 500개)
 *  flowvium:signal:accuracy:v1:{tf} — 타임프레임별 정확도 (JSON)
 *  flowvium:signal:thresholds:v1   — 현재 활성 임계값
 */

import type { Redis } from '@upstash/redis';

export const SIGNAL_LOG_KEY = 'flowvium:signal:log:v1';
export const SIGNAL_ACCURACY_PREFIX = 'flowvium:signal:accuracy:v1';
export const SIGNAL_THRESHOLDS_KEY = 'flowvium:signal:thresholds:v1';

export type Timeframe = '1w' | '4w' | '13w';

// 타임프레임 → 거래일 수
export const TF_TRADING_DAYS: Record<Timeframe, number> = { '1w': 5, '4w': 20, '13w': 65 };

// 현재 하드코딩된 기본 임계값 (정확도 낮으면 자동 조정)
export const DEFAULT_THRESHOLDS: Record<Timeframe, number> = { '1w': 0.5, '4w': 1.5, '13w': 3.0 };

export interface RotationSignal {
  id: string;            // uuid-like timestamp
  generatedAt: string;   // ISO
  evaluateAfter: string; // ISO (generatedAt + N trading days)
  timeframe: Timeframe;
  from: string;          // group/ticker losing
  fromTicker: string;    // ETF ticker for price verification
  to: string;            // group/ticker gaining
  toTicker: string;      // ETF ticker for price verification
  spread: number;        // % spread at signal time
  // Filled in after evaluation:
  evaluated?: boolean;
  toReturnActual?: number | null;   // actual return of 'to' after N days
  fromReturnActual?: number | null; // actual return of 'from' after N days
  hit?: boolean;         // true = 'to' outperformed 'from'
}

export interface AccuracyRecord {
  timeframe: Timeframe;
  hitRate: number;       // 0–1
  samples: number;
  currentThreshold: number;
  suggestedThreshold: number | null;
  lastUpdated: string;
}

/** Save rotation signals when generated by capital-flows route */
export async function logRotationSignals(
  redis: Redis,
  rotations: Array<{ from: string; to: string; magnitude: number }>,
  timeframe: Timeframe,
  tickerMap: Record<string, string>, // group → representative ETF ticker
): Promise<void> {
  if (!rotations.length) return;
  const now = new Date();
  const tradingDays = TF_TRADING_DAYS[timeframe];
  // Approximate trading days → calendar days (×1.4)
  const calendarMs = tradingDays * 1.4 * 86400000;
  const evaluateAfter = new Date(now.getTime() + calendarMs).toISOString();

  const signals: RotationSignal[] = rotations.slice(0, 5).map(r => ({
    id: `${timeframe}-${now.getTime()}-${r.from}-${r.to}`,
    generatedAt: now.toISOString(),
    evaluateAfter,
    timeframe,
    from: r.from,
    fromTicker: tickerMap[r.from] ?? r.from,
    to: r.to,
    toTicker: tickerMap[r.to] ?? r.to,
    spread: r.magnitude,
  }));

  try {
    for (const s of signals) {
      await redis.lpush(SIGNAL_LOG_KEY, JSON.stringify(s));
    }
    await redis.ltrim(SIGNAL_LOG_KEY, 0, 499); // cap at 500
  } catch { /* non-fatal */ }
}

/** Evaluate pending signals whose evaluateAfter has passed.
 *  Called by a cron job. Fetches actual returns via Yahoo Finance. */
export async function evaluatePendingSignals(
  redis: Redis,
  fetchReturn: (ticker: string, fromDate: string) => Promise<number | null>,
): Promise<{ evaluated: number; byTf: Record<Timeframe, number> }> {
  const now = new Date().toISOString();
  let evaluated = 0;
  const byTf: Record<Timeframe, number> = { '1w': 0, '4w': 0, '13w': 0 };

  try {
    const raw = await redis.lrange(SIGNAL_LOG_KEY, 0, 499);
    const signals: RotationSignal[] = raw.flatMap(r => {
      try { return [JSON.parse(r as string) as RotationSignal]; } catch { return []; }
    });

    const updated: RotationSignal[] = [];
    for (const s of signals) {
      if (s.evaluated || s.evaluateAfter > now) {
        updated.push(s);
        continue;
      }
      // Fetch actual returns
      const [toReturn, fromReturn] = await Promise.all([
        fetchReturn(s.toTicker, s.generatedAt),
        fetchReturn(s.fromTicker, s.generatedAt),
      ]);
      const hit = toReturn != null && fromReturn != null ? toReturn > fromReturn : null;
      updated.push({
        ...s,
        evaluated: true,
        toReturnActual: toReturn,
        fromReturnActual: fromReturn,
        hit: hit ?? undefined,
      });
      if (hit !== null) { evaluated++; byTf[s.timeframe]++; }
    }

    // Rewrite log
    if (evaluated > 0) {
      await redis.del(SIGNAL_LOG_KEY);
      for (const s of updated) {
        await redis.lpush(SIGNAL_LOG_KEY, JSON.stringify(s));
      }
      // Update accuracy per timeframe
      await updateAccuracy(redis, updated);
    }
  } catch { /* non-fatal */ }

  return { evaluated, byTf };
}

async function updateAccuracy(redis: Redis, signals: RotationSignal[]): Promise<void> {
  for (const tf of ['1w', '4w', '13w'] as Timeframe[]) {
    const evaluated = signals.filter(s => s.evaluated && s.hit !== undefined && s.timeframe === tf);
    if (!evaluated.length) continue;
    const hits = evaluated.filter(s => s.hit).length;
    const hitRate = hits / evaluated.length;

    // Karpathy-style threshold adjustment:
    // If hitRate < 0.55 → tighten (increase minSpread by 20%)
    // If hitRate > 0.75 → loosen (decrease by 10%)
    const current = DEFAULT_THRESHOLDS[tf];
    const suggested = hitRate < 0.55
      ? parseFloat((current * 1.2).toFixed(2))
      : hitRate > 0.75
        ? parseFloat((current * 0.9).toFixed(2))
        : null;

    const rec: AccuracyRecord = {
      timeframe: tf,
      hitRate: parseFloat(hitRate.toFixed(3)),
samples: evaluated.length,
      currentThreshold: current,
      suggestedThreshold: suggested,
      lastUpdated: new Date().toISOString(),
    };
    await redis.set(`${SIGNAL_ACCURACY_PREFIX}:${tf}`, JSON.stringify(rec), { ex: 180 * 86400 });
  }
}

/** Read current accuracy metrics (for UI display) */
export async function getSignalAccuracy(redis: Redis): Promise<Partial<Record<Timeframe, AccuracyRecord>>> {
  const result: Partial<Record<Timeframe, AccuracyRecord>> = {};
  for (const tf of ['1w', '4w', '13w'] as Timeframe[]) {
    try {
      const raw = await redis.get(`${SIGNAL_ACCURACY_PREFIX}:${tf}`);
      if (raw) result[tf] = JSON.parse(raw as string) as AccuracyRecord;
    } catch { /* ignore */ }
  }
  return result;
}

/** Get effective thresholds (suggested if accuracy improved, else defaults) */
export async function getEffectiveThresholds(redis: Redis): Promise<Record<Timeframe, number>> {
  const acc = await getSignalAccuracy(redis);
  return {
    '1w':  acc['1w']?.suggestedThreshold  ?? DEFAULT_THRESHOLDS['1w'],
    '4w':  acc['4w']?.suggestedThreshold  ?? DEFAULT_THRESHOLDS['4w'],
    '13w': acc['13w']?.suggestedThreshold ?? DEFAULT_THRESHOLDS['13w'],
  };
}
