import { readFileSync, writeFileSync } from 'fs';

const newKeys = {
  cfLoading: { ko:'글로벌 자금흐름 분석 중...', en:'Loading global capital flows...', ja:'グローバル資金フロー分析中...', 'zh-CN':'正在分析全球资金流向...', 'zh-TW':'正在分析全球資金流向...', es:'Analizando flujos de capital global...', fr:'Analyse des flux de capitaux mondiaux...', de:'Globale Kapitalflüsse werden analysiert...', pt:'Analisando fluxos de capital global...', ru:'Анализ глобальных потоков капитала...', ar:'جاري تحليل تدفقات رأس المال العالمية...', hi:'वैश्विक पूंजी प्रवाह विश्लेषण हो रहा है...', id:'Menganalisis aliran modal global...', th:'กำลังวิเคราะห์การไหลเวียนของเงินทุนทั่วโลก...', tr:'Küresel sermaye akışları analiz ediliyor...', vi:'Đang phân tích dòng vốn toàn cầu...' },
  cfLoadError: { ko:'데이터를 불러올 수 없습니다', en:'Failed to load data', ja:'データを読み込めません', 'zh-CN':'无法加载数据', 'zh-TW':'無法載入資料', es:'Error al cargar datos', fr:'Impossible de charger les données', de:'Daten konnten nicht geladen werden', pt:'Falha ao carregar dados', ru:'Не удалось загрузить данные', ar:'تعذر تحميل البيانات', hi:'डेटा लोड नहीं हो सका', id:'Gagal memuat data', th:'โหลดข้อมูลไม่ได้', tr:'Veriler yüklenemedi', vi:'Không thể tải dữ liệu' },
  cfPeriod: { ko:'기준', en:'Period', ja:'基準', 'zh-CN':'周期', 'zh-TW':'週期', es:'Período', fr:'Période', de:'Zeitraum', pt:'Período', ru:'Период', ar:'الفترة', hi:'अवधि', id:'Periode', th:'ช่วงเวลา', tr:'Dönem', vi:'Kỳ' },
  cfRotationTitle: { ko:'자금 로테이션', en:'Capital Rotation', ja:'資金ローテーション', 'zh-CN':'资金轮动', 'zh-TW':'資金輪動', es:'Rotación de Capital', fr:'Rotation du Capital', de:'Kapitalrotation', pt:'Rotação de Capital', ru:'Ротация капитала', ar:'دوران رأس المال', hi:'पूंजी रोटेशन', id:'Rotasi Modal', th:'การหมุนเวียนเงินทุน', tr:'Sermaye Rotasyonu', vi:'Luân chuyển vốn' },
  cfWeeksAgo: { ko:'{n}주 전 시작', en:'Started {n}w ago', ja:'{n}週前に開始', 'zh-CN':'{n}周前开始', 'zh-TW':'{n}週前開始', es:'Inicio hace {n}s', fr:'Débuté il y a {n}s', de:'Vor {n}W gestartet', pt:'Iniciou há {n}s', ru:'Начался {n}н назад', ar:'بدأ منذ {n} أسابيع', hi:'{n} हफ़्ते पहले शुरू', id:'Dimulai {n}m lalu', th:'เริ่ม {n} สัปดาห์ก่อน', tr:'{n} hafta önce başladı', vi:'Bắt đầu {n} tuần trước' },
  cfThisWeek: { ko:'이번 주 시작', en:'Started this week', ja:'今週開始', 'zh-CN':'本周开始', 'zh-TW':'本週開始', es:'Inicio esta semana', fr:'Débuté cette semaine', de:'Diese Woche gestartet', pt:'Iniciou esta semana', ru:'Начался на этой неделе', ar:'بدأ هذا الأسبوع', hi:'इस हफ़्ते शुरू', id:'Dimulai minggu ini', th:'เริ่มสัปดาห์นี้', tr:'Bu hafta başladı', vi:'Bắt đầu tuần này' },
  cfCountryTitle: { ko:'국가별 시장 자금 흐름', en:'Country Capital Flows', ja:'国別資金フロー', 'zh-CN':'各国市场资金流向', 'zh-TW':'各國市場資金流向', es:'Flujos por País', fr:'Flux par Pays', de:'Kapitalflüsse nach Land', pt:'Fluxos por País', ru:'Потоки капитала по странам', ar:'تدفقات رأس المال حسب الدولة', hi:'देश-वार पूंजी प्रवाह', id:'Aliran Modal per Negara', th:'การไหลเวียนเงินทุนรายประเทศ', tr:'Ülke Bazlı Sermaye Akışları', vi:'Dòng vốn theo quốc gia' },
  cfFactorTitle: { ko:'스마트베타 팩터 성과', en:'Smart Beta Factor Performance', ja:'スマートベータ成果', 'zh-CN':'智能贝塔因子表现', 'zh-TW':'智能貝塔因子表現', es:'Factores Smart Beta', fr:'Facteurs Smart Beta', de:'Smart-Beta-Faktoren', pt:'Fatores Smart Beta', ru:'Факторы Smart Beta', ar:'أداء عوامل Smart Beta', hi:'स्मार्ट बीटा फैक्टर', id:'Kinerja Smart Beta', th:'Smart Beta Factor', tr:'Smart Beta Faktörler', vi:'Yếu tố Smart Beta' },
  cfFactorNote: { ko:'iShares/MSCI 팩터 ETF 기반', en:'Based on iShares/MSCI Factor ETFs', ja:'iShares/MSCI ファクターETF', 'zh-CN':'基于iShares/MSCI因子ETF', 'zh-TW':'基於iShares/MSCI因子ETF', es:'Basado en ETFs iShares/MSCI', fr:'ETFs factoriels iShares/MSCI', de:'iShares/MSCI Faktor-ETFs', pt:'ETFs iShares/MSCI', ru:'iShares/MSCI факторные ETF', ar:'ETFs عوامل iShares/MSCI', hi:'iShares/MSCI फैक्टर ETF', id:'ETF Faktor iShares/MSCI', th:'iShares/MSCI Factor ETFs', tr:'iShares/MSCI Faktör ETF\'leri', vi:'ETF yếu tố iShares/MSCI' },
  cfSectorTitle: { ko:'미국 섹터 로테이션', en:'US Sector Rotation', ja:'米国セクターローテーション', 'zh-CN':'美国板块轮动', 'zh-TW':'美國板塊輪動', es:'Rotación Sectorial EE.UU.', fr:'Rotation Sectorielle US', de:'US-Sektorrotation', pt:'Rotação Setorial EUA', ru:'Ротация секторов США', ar:'دوران قطاعات الولايات المتحدة', hi:'अमेरिकी सेक्टर रोटेशन', id:'Rotasi Sektor AS', th:'การหมุนเวียนเซกเตอร์สหรัฐฯ', tr:'ABD Sektör Rotasyonu', vi:'Luân chuyển ngành Mỹ' },
  cfGoldDollarTitle: { ko:'금 vs 달러', en:'Gold vs Dollar', ja:'金 vs ドル', 'zh-CN':'黄金 vs 美元', 'zh-TW':'黃金 vs 美元', es:'Oro vs Dólar', fr:'Or vs Dollar', de:'Gold vs. Dollar', pt:'Ouro vs Dólar', ru:'Золото vs Доллар', ar:'الذهب مقابل الدولار', hi:'सोना बनाम डॉलर', id:'Emas vs Dolar', th:'ทองคำ vs ดอลลาร์', tr:'Altın vs Dolar', vi:'Vàng vs Đô la' },
  cfCurveTitle: { ko:'원자재 선물 커브 — 컨탱고 / 백워데이션', en:'Commodity Futures Curve — Contango / Backwardation', ja:'商品先物カーブ', 'zh-CN':'商品期货曲线', 'zh-TW':'商品期貨曲線', es:'Curva de Futuros', fr:'Courbe de Futures', de:'Futures-Kurve', pt:'Curva de Futuros', ru:'Фьючерсная кривая', ar:'منحنى العقود الآجلة', hi:'कमोडिटी फ्यूचर्स कर्व', id:'Kurva Futures', th:'เส้นโค้งฟิวเจอร์ส', tr:'Vadeli Eğrisi', vi:'Đường cong tương lai' },
  cfContango: { ko:'컨탱고 (정상상승)', en:'Contango (normal)', ja:'コンタンゴ', 'zh-CN':'正向市场', 'zh-TW':'正向市場', es:'Contango', fr:'Contango', de:'Contango', pt:'Contango', ru:'Контанго', ar:'كونتانغو', hi:'Contango', id:'Contango', th:'Contango', tr:'Contango', vi:'Contango' },
  cfBackwardation: { ko:'백워데이션 (공급부족)', en:'Backwardation (tight supply)', ja:'バックワーデーション', 'zh-CN':'反向市场', 'zh-TW':'反向市場', es:'Backwardation', fr:'Backwardation', de:'Backwardation', pt:'Backwardation', ru:'Бэквордация', ar:'باكووردايشن', hi:'Backwardation', id:'Backwardation', th:'Backwardation', tr:'Backwardation', vi:'Backwardation' },
  cfFlat: { ko:'플랫', en:'Flat', ja:'フラット', 'zh-CN':'平坦', 'zh-TW':'平坦', es:'Plano', fr:'Plat', de:'Flach', pt:'Plano', ru:'Плоский', ar:'مستوٍ', hi:'फ्लैट', id:'Datar', th:'แบน', tr:'Düz', vi:'Bằng phẳng' },
  cfOilBackwardation: { ko:'⚠️ 공급 타이트 — 현물 프리미엄', en:'⚠️ Tight supply — spot premium', ja:'⚠️ 供給逼迫 — 現物プレミアム', 'zh-CN':'⚠️ 供应紧张 — 现货溢价', 'zh-TW':'⚠️ 供應緊張 — 現貨溢價', es:'⚠️ Oferta ajustada — prima spot', fr:'⚠️ Offre tendue — prime spot', de:'⚠️ Knappes Angebot — Spot-Prämie', pt:'⚠️ Oferta restrita — prêmio spot', ru:'⚠️ Дефицит — спотовая премия', ar:'⚠️ إمدادات محدودة', hi:'⚠️ आपूर्ति तंग', id:'⚠️ Pasokan ketat — premi spot', th:'⚠️ อุปทานตึงตัว', tr:'⚠️ Arz kısıtlı — spot prim', vi:'⚠️ Cung khan hiếm' },
  cfOilContango: { ko:'📉 공급 여유 — 선도 프리미엄', en:'📉 Ample supply — forward premium', ja:'📉 供給余裕 — 先物プレミアム', 'zh-CN':'📉 供应充足 — 远期溢价', 'zh-TW':'📉 供應充足 — 遠期溢價', es:'📉 Oferta amplia — prima forward', fr:'📉 Offre abondante — prime forward', de:'📉 Reichlich Angebot — Forward-Prämie', pt:'📉 Oferta ampla — prêmio forward', ru:'📉 Достаточное предложение', ar:'📉 إمدادات وفيرة', hi:'📉 पर्याप्त आपूर्ति', id:'📉 Pasokan melimpah', th:'📉 อุปทานเพียงพอ', tr:'📉 Bol arz', vi:'📉 Nguồn cung dồi dào' },
  cfGoldContango: { ko:'📈 금 보유 비용 정상 반영', en:'📈 Normal gold carry cost', ja:'📈 金の保有コスト正常', 'zh-CN':'📈 黄金持有成本正常', 'zh-TW':'📈 黃金持有成本正常', es:'📈 Costo carry oro normal', fr:'📈 Portage or normal', de:'📈 Normale Goldhaltekosten', pt:'📈 Carry do ouro normal', ru:'📈 Нормальные затраты на хранение золота', ar:'📈 تكلفة حمل الذهب الطبيعية', hi:'📈 सामान्य सोना धारण लागत', id:'📈 Biaya carry emas normal', th:'📈 ต้นทุนถือครองทองคำปกติ', tr:'📈 Normal altın taşıma maliyeti', vi:'📈 Chi phí carry vàng bình thường' },
  cfGoldBackwardation: { ko:'⚠️ 금 현물 수요 급증 신호', en:'⚠️ Surge in gold spot demand', ja:'⚠️ 金現物需要急増', 'zh-CN':'⚠️ 黄金现货需求激增', 'zh-TW':'⚠️ 黃金現貨需求激增', es:'⚠️ Demanda spot oro elevada', fr:'⚠️ Forte demande spot or', de:'⚠️ Gold-Spot-Nachfrage steigt', pt:'⚠️ Demanda spot ouro alta', ru:'⚠️ Рост спотового спроса на золото', ar:'⚠️ ارتفاع الطلب الفوري على الذهب', hi:'⚠️ सोने की स्पॉट मांग उछाल', id:'⚠️ Permintaan spot emas melonjak', th:'⚠️ ความต้องการ gold spot เพิ่มสูง', tr:'⚠️ Altın spot talebinde artış', vi:'⚠️ Nhu cầu vàng giao ngay tăng vọt' },
  cfAssetReturnTitle: { ko:'자산군별 수익률 (자금 유입 방향)', en:'Asset Returns (Capital Flow Direction)', ja:'資産クラス別リターン', 'zh-CN':'资产类别收益', 'zh-TW':'資產類別收益', es:'Retornos por Activo', fr:'Rendements par Actif', de:'Renditen nach Anlage', pt:'Retornos por Ativo', ru:'Доходность по активам', ar:'عوائد الأصول', hi:'एसेट रिटर्न', id:'Imbal Hasil Aset', th:'ผลตอบแทนสินทรัพย์', tr:'Varlık Getirileri', vi:'Lợi nhuận tài sản' },
  cfTopInflow: { ko:'자금 유입 TOP 5', en:'Top 5 Inflows', ja:'資金流入 TOP 5', 'zh-CN':'资金流入 TOP 5', 'zh-TW':'資金流入 TOP 5', es:'Top 5 Entradas', fr:'Top 5 Entrées', de:'Top 5 Zuflüsse', pt:'Top 5 Entradas', ru:'Топ 5 притоков', ar:'أعلى 5 تدفقات واردة', hi:'टॉप 5 इनफ्लो', id:'Top 5 Masuk', th:'Top 5 เงินทุนไหลเข้า', tr:'En Yüksek 5 Giriş', vi:'Top 5 dòng vào' },
  cfTopOutflow: { ko:'자금 이탈 TOP 5', en:'Top 5 Outflows', ja:'資金流出 TOP 5', 'zh-CN':'资金流出 TOP 5', 'zh-TW':'資金流出 TOP 5', es:'Top 5 Salidas', fr:'Top 5 Sorties', de:'Top 5 Abflüsse', pt:'Top 5 Saídas', ru:'Топ 5 оттоков', ar:'أعلى 5 تدفقات صادرة', hi:'टॉप 5 आउटफ्लो', id:'Top 5 Keluar', th:'Top 5 เงินทุนไหลออก', tr:'En Yüksek 5 Çıkış', vi:'Top 5 dòng ra' },
  cfAllAssets: { ko:'전체 자산 수익률', en:'All Asset Returns', ja:'全資産リターン', 'zh-CN':'全部资产收益', 'zh-TW':'全部資產收益', es:'Todos los Activos', fr:'Tous les Actifs', de:'Alle Anlagen', pt:'Todos os Ativos', ru:'Все активы', ar:'جميع عوائد الأصول', hi:'सभी एसेट रिटर्न', id:'Semua Imbal Hasil', th:'ผลตอบแทนทั้งหมด', tr:'Tüm Varlık Getirileri', vi:'Tất cả lợi nhuận' },
  cfColAsset: { ko:'자산', en:'Asset', ja:'資産', 'zh-CN':'资产', 'zh-TW':'資產', es:'Activo', fr:'Actif', de:'Anlage', pt:'Ativo', ru:'Актив', ar:'الأصل', hi:'एसेट', id:'Aset', th:'สินทรัพย์', tr:'Varlık', vi:'Tài sản' },
  cfFootnote: { ko:'Yahoo Finance (15분 지연) · ETF 기반 분석 · 4시간 캐시', en:'Yahoo Finance (15-min delay) · ETF analysis · 4h cache', ja:'Yahoo Finance (15分遅延) · ETF分析 · 4時間キャッシュ', 'zh-CN':'Yahoo Finance (15分钟延迟) · ETF分析 · 4小时缓存', 'zh-TW':'Yahoo Finance (15分鐘延遲) · ETF分析 · 4小時緩存', es:'Yahoo Finance (15 min retraso) · ETF · 4h', fr:'Yahoo Finance (15 min) · ETF · 4h', de:'Yahoo Finance (15 Min.) · ETF · 4h', pt:'Yahoo Finance (15 min) · ETF · 4h', ru:'Yahoo Finance (15 мин) · ETF · 4ч', ar:'Yahoo Finance (15 دقيقة) · ETF · 4 ساعات', hi:'Yahoo Finance (15 मिनट) · ETF · 4h', id:'Yahoo Finance (15 menit) · ETF · 4j', th:'Yahoo Finance (15 นาที) · ETF · 4 ชม.', tr:'Yahoo Finance (15 dk) · ETF · 4s', vi:'Yahoo Finance (15 phút) · ETF · 4h' },
  cfUpdated: { ko:'업데이트', en:'Updated', ja:'更新', 'zh-CN':'更新', 'zh-TW':'更新', es:'Actualizado', fr:'Mis à jour', de:'Aktualisiert', pt:'Atualizado', ru:'Обновлено', ar:'محدّث', hi:'अपडेट', id:'Diperbarui', th:'อัปเดต', tr:'Güncellendi', vi:'Cập nhật' },
  cfGroupEquity: { ko:'주식', en:'Equities', ja:'株式', 'zh-CN':'股票', 'zh-TW':'股票', es:'Acciones', fr:'Actions', de:'Aktien', pt:'Ações', ru:'Акции', ar:'أسهم', hi:'इक्विटी', id:'Saham', th:'หุ้น', tr:'Hisseler', vi:'Cổ phiếu' },
  cfGroupBonds: { ko:'채권', en:'Bonds', ja:'債券', 'zh-CN':'债券', 'zh-TW':'債券', es:'Bonos', fr:'Obligations', de:'Anleihen', pt:'Títulos', ru:'Облигации', ar:'سندات', hi:'बॉन्ड', id:'Obligasi', th:'พันธบัตร', tr:'Tahviller', vi:'Trái phiếu' },
  cfGroupAlts: { ko:'대안자산', en:'Alternatives', ja:'オルタナティブ', 'zh-CN':'另类资产', 'zh-TW':'另類資產', es:'Alternativos', fr:'Alternatifs', de:'Alternativen', pt:'Alternativos', ru:'Альтернативы', ar:'بدائل', hi:'वैकल्पिक', id:'Alternatif', th:'สินทรัพย์ทางเลือก', tr:'Alternatifler', vi:'Thay thế' },
  cfGroupCommodities: { ko:'원자재', en:'Commodities', ja:'コモディティ', 'zh-CN':'大宗商品', 'zh-TW':'大宗商品', es:'Materias Primas', fr:'Matières Premières', de:'Rohstoffe', pt:'Commodities', ru:'Сырьё', ar:'سلع', hi:'कमोडिटी', id:'Komoditas', th:'สินค้าโภคภัณฑ์', tr:'Emtialar', vi:'Hàng hóa' },
  cfGroupCurrency: { ko:'통화', en:'Currency', ja:'通貨', 'zh-CN':'货币', 'zh-TW':'貨幣', es:'Divisas', fr:'Devises', de:'Währungen', pt:'Moedas', ru:'Валюты', ar:'عملات', hi:'मुद्रा', id:'Mata Uang', th:'สกุลเงิน', tr:'Dövizler', vi:'Tiền tệ' },
  cfTf1w: { ko:'1주', en:'1W', ja:'1週', 'zh-CN':'1周', 'zh-TW':'1週', es:'1S', fr:'1S', de:'1W', pt:'1S', ru:'1Н', ar:'1أ', hi:'1Wk', id:'1M', th:'1W', tr:'1H', vi:'1T' },
  cfTf4w: { ko:'4주', en:'4W', ja:'4週', 'zh-CN':'4周', 'zh-TW':'4週', es:'4S', fr:'4S', de:'4W', pt:'4S', ru:'4Н', ar:'4أ', hi:'4Wk', id:'4M', th:'4W', tr:'4H', vi:'4T' },
  cfTf13w: { ko:'3개월', en:'3M', ja:'3ヶ月', 'zh-CN':'3个月', 'zh-TW':'3個月', es:'3M', fr:'3M', de:'3M', pt:'3M', ru:'3М', ar:'3أشهر', hi:'3Mo', id:'3B', th:'3M', tr:'3A', vi:'3Th' },
  cfIntensityTitle: { ko:'수급 강도 & Cascade 영향', en:'Flow Intensity & Cascade Impact', ja:'需給強度 & カスケード影響', 'zh-CN':'资金强度 & 连锁影响', 'zh-TW':'資金強度 & 連鎖影響', es:'Intensidad & Cascada', fr:'Intensité & Cascade', de:'Flussintensität & Kaskade', pt:'Intensidade & Cascata', ru:'Интенсивность & Каскад', ar:'كثافة التدفق والتسلسل', hi:'प्रवाह तीव्रता & कैस्केड', id:'Intensitas & Kaskade', th:'ความเข้มของกระแสเงิน & Cascade', tr:'Yoğunluk & Kaskad', vi:'Cường độ & Dây chuyền' },
  cfIntensityCompare: { ko:'1w·4w·13w 비교', en:'1w·4w·13w Compare', ja:'1w·4w·13w 比較', 'zh-CN':'1w·4w·13w 对比', 'zh-TW':'1w·4w·13w 對比', es:'1s·4s·13s Comparar', fr:'1s·4s·13s Comparer', de:'1w·4w·13w Vergl.', pt:'1s·4s·13s', ru:'1н·4н·13н', ar:'مقارنة', hi:'1w·4w·13w', id:'Bandingkan', th:'เปรียบเทียบ', tr:'Karşılaştır', vi:'So sánh' },
  cfIntensityCascade: { ko:'Cascade 연쇄', en:'Cascade Chain', ja:'カスケード連鎖', 'zh-CN':'连锁效应', 'zh-TW':'連鎖效應', es:'Cadena Cascada', fr:'Chaîne Cascade', de:'Kaskadenkette', pt:'Cascata', ru:'Каскадная цепочка', ar:'سلسلة التسلسل', hi:'कैस्केड चेन', id:'Rantai Kaskade', th:'ลูกโซ่ Cascade', tr:'Kaskad Zinciri', vi:'Chuỗi dây chuyền' },
  cfInflows: { ko:'수급 유입 상위 (기간별)', en:'Top Inflows (by Period)', ja:'資金流入上位', 'zh-CN':'净流入前列', 'zh-TW':'淨流入前列', es:'Mayores Entradas', fr:'Principales Entrées', de:'Top-Zuflüsse', pt:'Principais Entradas', ru:'Топ притоков', ar:'أعلى التدفقات الواردة', hi:'शीर्ष इनफ्लो', id:'Masuk Teratas', th:'Top Inflows', tr:'En Yüksek Girişler', vi:'Top dòng vào' },
  cfOutflows: { ko:'수급 유출 상위 (기간별)', en:'Top Outflows (by Period)', ja:'資金流出上位', 'zh-CN':'净流出前列', 'zh-TW':'淨流出前列', es:'Mayores Salidas', fr:'Principales Sorties', de:'Top-Abflüsse', pt:'Principais Saídas', ru:'Топ оттоков', ar:'أعلى التدفقات الصادرة', hi:'शीर्ष आउटफ्लो', id:'Keluar Teratas', th:'Top Outflows', tr:'En Yüksek Çıkışlar', vi:'Top dòng ra' },
  cfColAssetCountry: { ko:'자산/국가', en:'Asset/Country', ja:'資産/国', 'zh-CN':'资产/国家', 'zh-TW':'資產/國家', es:'Activo/País', fr:'Actif/Pays', de:'Anlage/Land', pt:'Ativo/País', ru:'Актив/Страна', ar:'الأصل/الدولة', hi:'एसेट/देश', id:'Aset/Negara', th:'สินทรัพย์/ประเทศ', tr:'Varlık/Ülke', vi:'Tài sản/Quốc gia' },
  cfColDirection: { ko:'방향성', en:'Direction', ja:'方向性', 'zh-CN':'方向', 'zh-TW':'方向', es:'Dirección', fr:'Direction', de:'Richtung', pt:'Direção', ru:'Направление', ar:'الاتجاه', hi:'दिशा', id:'Arah', th:'ทิศทาง', tr:'Yön', vi:'Hướng' },
  cfTrendAccelerating: { ko:'가속▲', en:'Accel▲', ja:'加速▲', 'zh-CN':'加速▲', 'zh-TW':'加速▲', es:'Aceler▲', fr:'Accél▲', de:'Beschl▲', pt:'Aceler▲', ru:'Ускор▲', ar:'تسارع▲', hi:'तेज▲', id:'Accel▲', th:'เร่ง▲', tr:'Ivme▲', vi:'Tăng▲' },
  cfTrendReversing: { ko:'반전⚡', en:'Reverse⚡', ja:'反転⚡', 'zh-CN':'反转⚡', 'zh-TW':'反轉⚡', es:'Reverso⚡', fr:'Inverse⚡', de:'Umkehr⚡', pt:'Reverso⚡', ru:'Разворот⚡', ar:'انعكاس⚡', hi:'रिवर्स⚡', id:'Balik⚡', th:'กลับ⚡', tr:'Tersine⚡', vi:'Đảo⚡' },
  cfTrendHolding: { ko:'유지→', en:'Hold→', ja:'維持→', 'zh-CN':'维持→', 'zh-TW':'維持→', es:'Sostiene→', fr:'Maintient→', de:'Hält→', pt:'Mantém→', ru:'Держится→', ar:'يحافظ→', hi:'बनाए→', id:'Stabil→', th:'คง→', tr:'Sabit→', vi:'Giữ→' },
  cfTrendDecelerating: { ko:'가속▼', en:'Accel▼', ja:'加速▼', 'zh-CN':'加速▼', 'zh-TW':'加速▼', es:'Aceler▼', fr:'Accél▼', de:'Beschl▼', pt:'Aceler▼', ru:'Ускор▼', ar:'تسارع▼', hi:'तेज▼', id:'Accel▼', th:'เร่ง▼', tr:'Ivme▼', vi:'Tăng▼' },
  cfDivergenceAlert: { ko:'⚡ 추세 전환 감지 — 1주 vs 13주 방향 불일치', en:'⚡ Trend reversal — 1w vs 13w mismatch', ja:'⚡ トレンド転換 — 1週 vs 13週', 'zh-CN':'⚡ 趋势反转 — 1周 vs 13周', 'zh-TW':'⚡ 趨勢反轉 — 1週 vs 13週', es:'⚡ Reversión — 1s vs 13s', fr:'⚡ Retournement — 1s vs 13s', de:'⚡ Trendwende — 1w vs 13w', pt:'⚡ Reversão — 1s vs 13s', ru:'⚡ Разворот — 1н vs 13н', ar:'⚡ انعكاس الاتجاه', hi:'⚡ ट्रेंड रिवर्सल — 1w vs 13w', id:'⚡ Pembalikan tren', th:'⚡ กลับทิศ — 1w vs 13w', tr:'⚡ Trend dönüşü — 1h vs 13h', vi:'⚡ Đảo chiều — 1t vs 13t' },
  cfCascadeDesc: { ko:'4주 기준 상위 유입 자산/국가의 연쇄 영향', en:'Cascade impact of top 4w inflow assets/countries', ja:'4週間上位流入のカスケード影響', 'zh-CN':'4周主要流入的连锁影响', 'zh-TW':'4週主要流入的連鎖影響', es:'Impacto cascada de activos top 4s', fr:'Impact cascade des actifs 4s', de:'Kaskadeneffekt Top 4w', pt:'Impacto cascata top 4s', ru:'Каскадный эффект топ 4н', ar:'التأثير التسلسلي للأصول الأعلى تدفقاً 4 أسابيع', hi:'शीर्ष 4w इनफ्लो का कैस्केड प्रभाव', id:'Dampak kaskade aliran masuk top 4m', th:'ผลกระทบแบบลูกโซ่ของ 4w top inflows', tr:'En yüksek 4h girişin kaskad etkisi', vi:'Tác động dây chuyền top 4t' },
  cfBenefiting: { ko:'수혜 ↑', en:'Benefiting ↑', ja:'恩恵 ↑', 'zh-CN':'受益 ↑', 'zh-TW':'受益 ↑', es:'Beneficia ↑', fr:'Bénéficie ↑', de:'Profitiert ↑', pt:'Beneficia ↑', ru:'Выигрывает ↑', ar:'مستفيد ↑', hi:'लाभार्थी ↑', id:'Untung ↑', th:'ได้ประโยชน์ ↑', tr:'Yarar ↑', vi:'Hưởng lợi ↑' },
  cfHarmed: { ko:'피해 ↓', en:'Harmed ↓', ja:'打撃 ↓', 'zh-CN':'受损 ↓', 'zh-TW':'受損 ↓', es:'Perjudica ↓', fr:'Nuit ↓', de:'Schadet ↓', pt:'Prejudica ↓', ru:'Страдает ↓', ar:'متضرر ↓', hi:'नुकसान ↓', id:'Rugi ↓', th:'เสียหาย ↓', tr:'Zarar ↓', vi:'Tổn hại ↓' },
  cfCascadeNoData: { ko:'Cascade 데이터 없음', en:'No Cascade data', ja:'カスケードデータなし', 'zh-CN':'无连锁数据', 'zh-TW':'無連鎖數據', es:'Sin datos Cascada', fr:'Pas de données Cascade', de:'Keine Kaskadendaten', pt:'Sem dados Cascata', ru:'Нет данных каскада', ar:'لا توجد بيانات', hi:'Cascade डेटा नहीं', id:'Tidak ada data Kaskade', th:'ไม่มีข้อมูล Cascade', tr:'Kaskad verisi yok', vi:'Không có dữ liệu Cascade' },
  cfAiTitle: { ko:'AI 자금흐름 원인 분석', en:'AI Capital Flow Analysis', ja:'AI資金フロー分析', 'zh-CN':'AI资金流向分析', 'zh-TW':'AI資金流向分析', es:'Análisis IA de Flujos', fr:'Analyse IA des Flux', de:'KI-Kapitalfluss-Analyse', pt:'Análise IA de Fluxos', ru:'ИИ-анализ потоков', ar:'تحليل AI لتدفقات رأس المال', hi:'AI पूंजी प्रवाह विश्लेषण', id:'Analisis Aliran AI', th:'AI วิเคราะห์กระแสเงินทุน', tr:'AI Sermaye Akış Analizi', vi:'Phân tích dòng vốn AI' },
  cfAiSubtitle: { ko:'EXAONE이 각 국가의 자금흐름 원인과 로테이션 이유를 분석합니다', en:'EXAONE analyzes capital flow causes and rotation by country', ja:'EXAONEが各国の資金フロー要因を分析します', 'zh-CN':'EXAONE分析各国资金流动原因', 'zh-TW':'EXAONE分析各國資金流動原因', es:'EXAONE analiza flujos y rotaciones por país', fr:'EXAONE analyse flux et rotations par pays', de:'EXAONE analysiert Kapitalflüsse nach Land', pt:'EXAONE analisa fluxos e rotações por país', ru:'EXAONE анализирует потоки и ротации по странам', ar:'يحلل EXAONE تدفقات رأس المال حسب الدولة', hi:'EXAONE प्रत्येक देश के पूंजी प्रवाह का विश्लेषण करता है', id:'EXAONE menganalisis aliran modal per negara', th:'EXAONE วิเคราะห์กระแสเงินทุนรายประเทศ', tr:'EXAONE ülkelere göre sermaye akışlarını analiz eder', vi:'EXAONE phân tích dòng vốn theo quốc gia' },
  cfAiStart: { ko:'원인 분석 시작', en:'Start Analysis', ja:'分析開始', 'zh-CN':'开始分析', 'zh-TW':'開始分析', es:'Iniciar Análisis', fr:'Démarrer l\'Analyse', de:'Analyse starten', pt:'Iniciar Análise', ru:'Начать анализ', ar:'بدء التحليل', hi:'विश्लेषण शुरू करें', id:'Mulai Analisis', th:'เริ่มการวิเคราะห์', tr:'Analizi Başlat', vi:'Bắt đầu phân tích' },
  cfAiAnalyzing: { ko:'EXAONE이 자금흐름 원인 분석 중...', en:'EXAONE analyzing capital flows...', ja:'EXAONEが分析中...', 'zh-CN':'EXAONE正在分析...', 'zh-TW':'EXAONE正在分析...', es:'EXAONE analizando flujos...', fr:'EXAONE analyse...', de:'EXAONE analysiert...', pt:'EXAONE analisando...', ru:'EXAONE анализирует...', ar:'EXAONE يحلل...', hi:'EXAONE विश्लेषण कर रहा है...', id:'EXAONE menganalisis...', th:'EXAONE กำลังวิเคราะห์...', tr:'EXAONE analiz ediyor...', vi:'EXAONE đang phân tích...' },
  cfAiAnalyzingDesc: { ko:'국가별 ETF 수익률과 글로벌 이벤트 데이터를 분석하고 있어요', en:'Analyzing country ETF returns and global event data', ja:'各国ETFリターンとグローバルイベントを分析中', 'zh-CN':'正在分析各国ETF收益和全球事件数据', 'zh-TW':'正在分析各國ETF收益和全球事件數據', es:'Analizando ETFs y eventos globales', fr:'Analyse ETFs et événements mondiaux', de:'ETF-Renditen und globale Ereignisse werden analysiert', pt:'Analisando ETFs e eventos globais', ru:'Анализ ETF и глобальных событий', ar:'تحليل ETF الدولي والأحداث العالمية', hi:'देश ETF और वैश्विक घटनाओं का विश्लेषण', id:'Menganalisis ETF dan peristiwa global', th:'วิเคราะห์ ETF รายประเทศและเหตุการณ์โลก', tr:'Ülke ETF getirileri analiz ediliyor', vi:'Phân tích ETF và sự kiện toàn cầu' },
  cfAiLoadError: { ko:'분석을 불러오지 못했습니다. AI 서버 연결을 확인해주세요.', en:'Failed to load analysis. Check AI server connection.', ja:'分析の読み込みに失敗しました。', 'zh-CN':'无法加载分析。请检查AI服务器。', 'zh-TW':'無法載入分析。請檢查AI伺服器。', es:'Error al cargar análisis.', fr:'Échec du chargement de l\'analyse.', de:'Analyse nicht geladen. KI-Server prüfen.', pt:'Falha ao carregar análise.', ru:'Не удалось загрузить анализ.', ar:'تعذر تحميل التحليل.', hi:'विश्लेषण लोड नहीं हुआ।', id:'Gagal memuat analisis.', th:'โหลดการวิเคราะห์ไม่ได้', tr:'Analiz yüklenemedi.', vi:'Không thể tải phân tích.' },
  cfAiRetry: { ko:'다시 시도', en:'Retry', ja:'再試行', 'zh-CN':'重试', 'zh-TW':'重試', es:'Reintentar', fr:'Réessayer', de:'Wiederholen', pt:'Tentar novamente', ru:'Повторить', ar:'إعادة المحاولة', hi:'पुनः प्रयास', id:'Coba Lagi', th:'ลองใหม่', tr:'Yeniden Dene', vi:'Thử lại' },
  cfAiCacheInfo: { ko:'생성 · 4시간 캐시', en:'Generated · 4h cache', ja:'生成済 · 4時間', 'zh-CN':'已生成 · 4小时缓存', 'zh-TW':'已生成 · 4小時緩存', es:'Generado · 4h', fr:'Généré · 4h', de:'Generiert · 4h', pt:'Gerado · 4h', ru:'Создано · 4ч', ar:'مُنشأ · 4 ساعات', hi:'उत्पन्न · 4h', id:'Dibuat · 4j', th:'สร้างแล้ว · 4 ชม.', tr:'Oluşturuldu · 4s', vi:'Đã tạo · 4h' },
  cfAiTheme: { ko:'현재 핵심 테마', en:'Current Key Theme', ja:'現在の主要テーマ', 'zh-CN':'当前核心主题', 'zh-TW':'當前核心主題', es:'Tema Clave Actual', fr:'Thème Clé Actuel', de:'Aktuelles Kernthema', pt:'Tema Principal Atual', ru:'Текущая тема', ar:'الموضوع الرئيسي الحالي', hi:'वर्तमान मुख्य विषय', id:'Tema Kunci Saat Ini', th:'ธีมหลักปัจจุบัน', tr:'Mevcut Anahtar Tema', vi:'Chủ đề chính hiện tại' },
  cfAiSummary: { ko:'📋 전체 요약', en:'📋 Summary', ja:'📋 サマリー', 'zh-CN':'📋 总结', 'zh-TW':'📋 總結', es:'📋 Resumen', fr:'📋 Résumé', de:'📋 Zusammenfassung', pt:'📋 Resumo', ru:'📋 Сводка', ar:'📋 ملخص', hi:'📋 सारांश', id:'📋 Ringkasan', th:'📋 สรุป', tr:'📋 Özet', vi:'📋 Tóm tắt' },
  cfAiByCountry: { ko:'국가별 원인 분석', en:'Analysis by Country', ja:'国別分析', 'zh-CN':'各国分析', 'zh-TW':'各國分析', es:'Análisis por País', fr:'Analyse par Pays', de:'Länderanalyse', pt:'Análise por País', ru:'Анализ по странам', ar:'تحليل حسب الدولة', hi:'देश-वार विश्लेषण', id:'Analisis per Negara', th:'วิเคราะห์รายประเทศ', tr:'Ülke Bazlı Analiz', vi:'Phân tích theo quốc gia' },
  cfAiRotation: { ko:'로테이션 원인', en:'Rotation Causes', ja:'ローテーション要因', 'zh-CN':'轮动原因', 'zh-TW':'輪動原因', es:'Causas de Rotación', fr:'Causes de Rotation', de:'Rotationsgründe', pt:'Causas de Rotação', ru:'Причины ротации', ar:'أسباب التدوير', hi:'रोटेशन के कारण', id:'Penyebab Rotasi', th:'สาเหตุการหมุนเวียน', tr:'Rotasyon Nedenleri', vi:'Nguyên nhân luân chuyển' },
  cfAiWatchpoints: { ko:'👀 지금 주목해야 할 포인트', en:'👀 Key Watch Points', ja:'👀 注目ポイント', 'zh-CN':'👀 关注要点', 'zh-TW':'👀 關注要點', es:'👀 Puntos Clave', fr:'👀 Points de Vigilance', de:'👀 Beobachtungspunkte', pt:'👀 Pontos de Atenção', ru:'👀 Ключевые точки', ar:'👀 نقاط الاهتمام', hi:'👀 मुख्य बिंदु', id:'👀 Poin Pengamatan', th:'👀 จุดสังเกต', tr:'👀 İzleme Noktaları', vi:'👀 Điểm theo dõi' },
};

const langs = ['ko','en','ja','zh-CN','zh-TW','es','fr','de','pt','ru','ar','hi','id','th','tr','vi'];
let updated = 0;
for (const lang of langs) {
  const filePath = `messages/${lang}.json`;
  const data = JSON.parse(readFileSync(filePath, 'utf8'));
  if (!data.intelligence) data.intelligence = {};
  let changed = false;
  for (const [key, translations] of Object.entries(newKeys)) {
    if (!data.intelligence[key]) {
      data.intelligence[key] = translations[lang] ?? translations['en'];
      changed = true;
    }
  }
  if (changed) {
    writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
    updated++;
  }
}
console.log(`Updated ${updated} language files`);
