import json
import os

MESSAGES_DIR = "messages"

NEW_KEYS = {
    "ar": {
        "ncSentimentBullish": "صعودي",
        "ncSentimentBearish": "هبوطي",
        "ncSentimentNeutral": "محايد",
        "ncLoading": "جار تحليل الأخبار...",
        "ncEmpty": "تعذر تحميل بيانات News Cascade. يرجى المحاولة لاحقاً.",
        "ncTitle": "تحليل تأثير الأخبار على السوق (Cascade)",
        "ncDesc": "يحلل الذكاء الاصطناعي الأخبار الرئيسية للتنبؤ بالتأثيرات المتسلسلة على الأصول والقطاعات. 🔴 أهمية عالية · 🟡 متوسط · ⚪ منخفض",
        "ncCascadeExpand": "Cascade {count} عرض",
        "ncCascadeCollapse": "Cascade {count} طي",
        "ncMagHigh": "ع",
        "ncMagMedium": "م",
        "ncMagLow": "ض",
        "ecToday": "اليوم",
        "ecTomorrow": "غداً",
        "ecDaysLater": "بعد {days}ي",
        "ecTitle": "تقويم الأحداث الاقتصادية الكلية",
        "ecTimezone": "ET",
        "ecFootnote": "المصدر: Federal Reserve · BLS · BEA · قد تتغير التواريخ"
    },
    "de": {
        "ncSentimentBullish": "Bullish",
        "ncSentimentBearish": "Bearish",
        "ncSentimentNeutral": "Neutral",
        "ncLoading": "Nachrichten werden analysiert...",
        "ncEmpty": "News-Cascade-Daten konnten nicht geladen werden. Bitte später erneut versuchen.",
        "ncTitle": "Nachrichten-Markt-Kaskadenanalyse",
        "ncDesc": "KI analysiert wichtige Nachrichten, um Kaskadeneffekte auf Vermögenswerte und Sektoren vorherzusagen. 🔴 Hoch · 🟡 Mittel · ⚪ Niedrig",
        "ncCascadeExpand": "Kaskade {count} anzeigen",
        "ncCascadeCollapse": "Kaskade {count} ausblenden",
        "ncMagHigh": "H",
        "ncMagMedium": "M",
        "ncMagLow": "N",
        "ecToday": "Heute",
        "ecTomorrow": "Morgen",
        "ecDaysLater": "In {days}T",
        "ecTitle": "Wichtige Makroereignisse",
        "ecTimezone": "ET",
        "ecFootnote": "Quelle: Federal Reserve · BLS · BEA · Termine können sich ändern"
    },
    "en": {
        "ncSentimentBullish": "Bullish",
        "ncSentimentBearish": "Bearish",
        "ncSentimentNeutral": "Neutral",
        "ncLoading": "Analyzing news...",
        "ncEmpty": "Unable to load News Cascade data. Please try again later.",
        "ncTitle": "News Market Cascade Analysis",
        "ncDesc": "AI analyzes major news to predict cascading effects on assets & sectors. 🔴 High importance · 🟡 Medium · ⚪ Low",
        "ncCascadeExpand": "Cascade {count} Show",
        "ncCascadeCollapse": "Cascade {count} Hide",
        "ncMagHigh": "H",
        "ncMagMedium": "M",
        "ncMagLow": "L",
        "ecToday": "Today",
        "ecTomorrow": "Tomorrow",
        "ecDaysLater": "In {days}d",
        "ecTitle": "Key Macro Events Calendar",
        "ecTimezone": "ET",
        "ecFootnote": "Source: Federal Reserve · BLS · BEA official schedule · Dates subject to change"
    },
    "es": {
        "ncSentimentBullish": "Alcista",
        "ncSentimentBearish": "Bajista",
        "ncSentimentNeutral": "Neutral",
        "ncLoading": "Analizando noticias...",
        "ncEmpty": "No se pudieron cargar los datos de News Cascade. Por favor, intente más tarde.",
        "ncTitle": "Análisis de Cascada de Noticias del Mercado",
        "ncDesc": "La IA analiza noticias importantes para predecir efectos en cascada en activos y sectores. 🔴 Alta importancia · 🟡 Media · ⚪ Baja",
        "ncCascadeExpand": "Cascada {count} Ver",
        "ncCascadeCollapse": "Cascada {count} Ocultar",
        "ncMagHigh": "A",
        "ncMagMedium": "M",
        "ncMagLow": "B",
        "ecToday": "Hoy",
        "ecTomorrow": "Mañana",
        "ecDaysLater": "En {days}d",
        "ecTitle": "Calendario de Eventos Macro Clave",
        "ecTimezone": "ET",
        "ecFootnote": "Fuente: Federal Reserve · BLS · BEA · Las fechas pueden cambiar"
    },
    "fr": {
        "ncSentimentBullish": "Haussier",
        "ncSentimentBearish": "Baissier",
        "ncSentimentNeutral": "Neutre",
        "ncLoading": "Analyse des actualités...",
        "ncEmpty": "Impossible de charger les données News Cascade. Veuillez réessayer plus tard.",
        "ncTitle": "Analyse en Cascade des Actualités du Marché",
        "ncDesc": "IA analyse les actualités majeures pour prédire les effets en cascade sur les actifs et secteurs. 🔴 Haute importance · 🟡 Moyenne · ⚪ Faible",
        "ncCascadeExpand": "Cascade {count} Voir",
        "ncCascadeCollapse": "Cascade {count} Réduire",
        "ncMagHigh": "H",
        "ncMagMedium": "M",
        "ncMagLow": "F",
        "ecToday": "Aujourd'hui",
        "ecTomorrow": "Demain",
        "ecDaysLater": "Dans {days}j",
        "ecTitle": "Calendrier des Événements Macro Clés",
        "ecTimezone": "ET",
        "ecFootnote": "Source : Federal Reserve · BLS · BEA · Les dates peuvent changer"
    },
    "hi": {
        "ncSentimentBullish": "बुलिश",
        "ncSentimentBearish": "बियरिश",
        "ncSentimentNeutral": "तटस्थ",
        "ncLoading": "समाचार विश्लेषण जारी...",
        "ncEmpty": "News Cascade डेटा लोड नहीं हो सका। कृपया बाद में पुनः प्रयास करें।",
        "ncTitle": "समाचार बाज़ार कैस्केड विश्लेषण",
        "ncDesc": "AI प्रमुख समाचारों का विश्लेषण करके संपत्तियों और क्षेत्रों पर कैस्केडिंग प्रभाव की भविष्यवाणी करता है। 🔴 उच्च · 🟡 मध्यम · ⚪ कम",
        "ncCascadeExpand": "Cascade {count} देखें",
        "ncCascadeCollapse": "Cascade {count} छुपाएं",
        "ncMagHigh": "उ",
        "ncMagMedium": "म",
        "ncMagLow": "न",
        "ecToday": "आज",
        "ecTomorrow": "कल",
        "ecDaysLater": "{days} दिन बाद",
        "ecTitle": "प्रमुख मैक्रो इवेंट कैलेंडर",
        "ecTimezone": "ET",
        "ecFootnote": "स्रोत: Federal Reserve · BLS · BEA · तिथियां बदल सकती हैं"
    },
    "id": {
        "ncSentimentBullish": "Bullish",
        "ncSentimentBearish": "Bearish",
        "ncSentimentNeutral": "Netral",
        "ncLoading": "Menganalisis berita...",
        "ncEmpty": "Gagal memuat data News Cascade. Silakan coba lagi nanti.",
        "ncTitle": "Analisis Kaskade Berita Pasar",
        "ncDesc": "AI menganalisis berita utama untuk memprediksi efek berantai pada aset dan sektor. 🔴 Penting tinggi · 🟡 Sedang · ⚪ Rendah",
        "ncCascadeExpand": "Cascade {count} Lihat",
        "ncCascadeCollapse": "Cascade {count} Tutup",
        "ncMagHigh": "T",
        "ncMagMedium": "S",
        "ncMagLow": "R",
        "ecToday": "Hari ini",
        "ecTomorrow": "Besok",
        "ecDaysLater": "{days}h lagi",
        "ecTitle": "Kalender Acara Makro Utama",
        "ecTimezone": "ET",
        "ecFootnote": "Sumber: Federal Reserve · BLS · BEA · Tanggal dapat berubah"
    },
    "ja": {
        "ncSentimentBullish": "強気",
        "ncSentimentBearish": "弱気",
        "ncSentimentNeutral": "中立",
        "ncLoading": "ニュース分析中...",
        "ncEmpty": "ニュースCascadeデータを読み込めませんでした。後でもう一度お試しください。",
        "ncTitle": "ニュース市場カスケード分析",
        "ncDesc": "AIが主要ニュースを分析し、各資産・セクターへの連鎖的影響を予測します。🔴 重要度高 · 🟡 中 · ⚪ 低",
        "ncCascadeExpand": "Cascade {count}件 表示",
        "ncCascadeCollapse": "Cascade {count}件 閉じる",
        "ncMagHigh": "強",
        "ncMagMedium": "中",
        "ncMagLow": "弱",
        "ecToday": "今日",
        "ecTomorrow": "明日",
        "ecDaysLater": "{days}日後",
        "ecTitle": "主要マクロイベントカレンダー",
        "ecTimezone": "ET基準",
        "ecFootnote": "出典: Federal Reserve · BLS · BEA公式発表日程 · 日程は変更される場合があります"
    },
    "ko": {
        "ncSentimentBullish": "강세",
        "ncSentimentBearish": "약세",
        "ncSentimentNeutral": "중립",
        "ncLoading": "뉴스 분석 중...",
        "ncEmpty": "뉴스 Cascade 데이터를 불러올 수 없습니다. 잠시 후 다시 시도해주세요.",
        "ncTitle": "뉴스 시장 파급 분석 (Cascade)",
        "ncDesc": "AI가 주요 뉴스를 분석해 각 자산·섹터에 미치는 연쇄 영향을 예측합니다. 🔴 중요도 높음 · 🟡 중간 · ⚪ 낮음",
        "ncCascadeExpand": "Cascade {count}개 보기",
        "ncCascadeCollapse": "Cascade {count}개 접기",
        "ncMagHigh": "강",
        "ncMagMedium": "중",
        "ncMagLow": "약",
        "ecToday": "오늘",
        "ecTomorrow": "내일",
        "ecDaysLater": "{days}일 후",
        "ecTitle": "주요 매크로 이벤트 캘린더",
        "ecTimezone": "ET 기준",
        "ecFootnote": "출처: Federal Reserve · BLS · BEA 공식 발표 일정 · 날짜는 변경될 수 있습니다"
    },
    "pt": {
        "ncSentimentBullish": "Alta",
        "ncSentimentBearish": "Baixa",
        "ncSentimentNeutral": "Neutro",
        "ncLoading": "Analisando notícias...",
        "ncEmpty": "Não foi possível carregar dados do News Cascade. Tente novamente mais tarde.",
        "ncTitle": "Análise em Cascata de Notícias do Mercado",
        "ncDesc": "A IA analisa as principais notícias para prever efeitos em cascata em ativos e setores. 🔴 Alta importância · 🟡 Média · ⚪ Baixa",
        "ncCascadeExpand": "Cascade {count} Ver",
        "ncCascadeCollapse": "Cascade {count} Ocultar",
        "ncMagHigh": "A",
        "ncMagMedium": "M",
        "ncMagLow": "B",
        "ecToday": "Hoje",
        "ecTomorrow": "Amanhã",
        "ecDaysLater": "Em {days}d",
        "ecTitle": "Calendário de Eventos Macro Principais",
        "ecTimezone": "ET",
        "ecFootnote": "Fonte: Federal Reserve · BLS · BEA · Datas sujeitas a alteração"
    },
    "ru": {
        "ncSentimentBullish": "Бычий",
        "ncSentimentBearish": "Медвежий",
        "ncSentimentNeutral": "Нейтральный",
        "ncLoading": "Анализ новостей...",
        "ncEmpty": "Не удалось загрузить данные News Cascade. Попробуйте позже.",
        "ncTitle": "Анализ каскадного влияния новостей на рынок",
        "ncDesc": "ИИ анализирует ключевые новости для прогноза каскадных эффектов на активы и секторы. 🔴 Высокая важность · 🟡 Средняя · ⚪ Низкая",
        "ncCascadeExpand": "Cascade {count} показать",
        "ncCascadeCollapse": "Cascade {count} скрыть",
        "ncMagHigh": "В",
        "ncMagMedium": "С",
        "ncMagLow": "Н",
        "ecToday": "Сегодня",
        "ecTomorrow": "Завтра",
        "ecDaysLater": "Через {days}д",
        "ecTitle": "Ключевые макроэкономические события",
        "ecTimezone": "ET",
        "ecFootnote": "Источник: Federal Reserve · BLS · BEA · Даты могут измениться"
    },
    "th": {
        "ncSentimentBullish": "กระทิง",
        "ncSentimentBearish": "หมี",
        "ncSentimentNeutral": "เป็นกลาง",
        "ncLoading": "กำลังวิเคราะห์ข่าว...",
        "ncEmpty": "ไม่สามารถโหลดข้อมูล News Cascade ได้ กรุณาลองใหม่อีกครั้ง",
        "ncTitle": "การวิเคราะห์ผลกระทบข่าวต่อตลาด",
        "ncDesc": "AI วิเคราะห์ข่าวสำคัญเพื่อทำนายผลกระทบต่อเนื่องต่อสินทรัพย์และเซกเตอร์ 🔴 สำคัญมาก · 🟡 ปานกลาง · ⚪ น้อย",
        "ncCascadeExpand": "Cascade {count} รายการ ดู",
        "ncCascadeCollapse": "Cascade {count} รายการ ซ่อน",
        "ncMagHigh": "ส",
        "ncMagMedium": "ก",
        "ncMagLow": "ต",
        "ecToday": "วันนี้",
        "ecTomorrow": "พรุ่งนี้",
        "ecDaysLater": "อีก {days} วัน",
        "ecTitle": "ปฏิทินเหตุการณ์เศรษฐกิจมหภาค",
        "ecTimezone": "ET",
        "ecFootnote": "แหล่งข้อมูล: Federal Reserve · BLS · BEA · วันที่อาจเปลี่ยนแปลงได้"
    },
    "tr": {
        "ncSentimentBullish": "Yükselen",
        "ncSentimentBearish": "Düşen",
        "ncSentimentNeutral": "Nötr",
        "ncLoading": "Haberler analiz ediliyor...",
        "ncEmpty": "News Cascade verileri yüklenemedi. Lütfen daha sonra tekrar deneyin.",
        "ncTitle": "Haber Piyasa Kaskad Analizi",
        "ncDesc": "Yapay zeka, varlıklar ve sektörler üzerindeki kaskad etkilerini tahmin etmek için önemli haberleri analiz eder. 🔴 Yüksek önem · 🟡 Orta · ⚪ Düşük",
        "ncCascadeExpand": "Cascade {count} Göster",
        "ncCascadeCollapse": "Cascade {count} Gizle",
        "ncMagHigh": "Y",
        "ncMagMedium": "O",
        "ncMagLow": "D",
        "ecToday": "Bugün",
        "ecTomorrow": "Yarın",
        "ecDaysLater": "{days}g sonra",
        "ecTitle": "Önemli Makro Etkinlikler Takvimi",
        "ecTimezone": "ET",
        "ecFootnote": "Kaynak: Federal Reserve · BLS · BEA · Tarihler değişebilir"
    },
    "vi": {
        "ncSentimentBullish": "Tăng",
        "ncSentimentBearish": "Giảm",
        "ncSentimentNeutral": "Trung lập",
        "ncLoading": "Đang phân tích tin tức...",
        "ncEmpty": "Không thể tải dữ liệu News Cascade. Vui lòng thử lại sau.",
        "ncTitle": "Phân Tích Tác Động Tin Tức Theo Chuỗi",
        "ncDesc": "AI phân tích tin tức quan trọng để dự đoán tác động dây chuyền lên tài sản và ngành. 🔴 Quan trọng cao · 🟡 Trung bình · ⚪ Thấp",
        "ncCascadeExpand": "Cascade {count} Xem",
        "ncCascadeCollapse": "Cascade {count} Ẩn",
        "ncMagHigh": "C",
        "ncMagMedium": "T",
        "ncMagLow": "T",
        "ecToday": "Hôm nay",
        "ecTomorrow": "Ngày mai",
        "ecDaysLater": "{days}ng nữa",
        "ecTitle": "Lịch Sự Kiện Kinh Tế Vĩ Mô",
        "ecTimezone": "ET",
        "ecFootnote": "Nguồn: Federal Reserve · BLS · BEA · Ngày có thể thay đổi"
    },
    "zh-CN": {
        "ncSentimentBullish": "看涨",
        "ncSentimentBearish": "看跌",
        "ncSentimentNeutral": "中性",
        "ncLoading": "新闻分析中...",
        "ncEmpty": "无法加载新闻Cascade数据，请稍后重试。",
        "ncTitle": "新闻市场连锁影响分析",
        "ncDesc": "AI分析重要新闻，预测对各资产和板块的连锁影响。🔴 重要度高 · 🟡 中 · ⚪ 低",
        "ncCascadeExpand": "Cascade {count}个 展开",
        "ncCascadeCollapse": "Cascade {count}个 收起",
        "ncMagHigh": "强",
        "ncMagMedium": "中",
        "ncMagLow": "弱",
        "ecToday": "今天",
        "ecTomorrow": "明天",
        "ecDaysLater": "{days}天后",
        "ecTitle": "主要宏观事件日历",
        "ecTimezone": "美东时间",
        "ecFootnote": "来源：Federal Reserve · BLS · BEA · 日期可能变更"
    },
    "zh-TW": {
        "ncSentimentBullish": "看漲",
        "ncSentimentBearish": "看跌",
        "ncSentimentNeutral": "中性",
        "ncLoading": "新聞分析中...",
        "ncEmpty": "無法載入新聞Cascade資料，請稍後重試。",
        "ncTitle": "新聞市場連鎖影響分析",
        "ncDesc": "AI分析重要新聞，預測對各資產和板塊的連鎖影響。🔴 重要度高 · 🟡 中 · ⚪ 低",
        "ncCascadeExpand": "Cascade {count}個 展開",
        "ncCascadeCollapse": "Cascade {count}個 收起",
        "ncMagHigh": "強",
        "ncMagMedium": "中",
        "ncMagLow": "弱",
        "ecToday": "今天",
        "ecTomorrow": "明天",
        "ecDaysLater": "{days}天後",
        "ecTitle": "主要宏觀事件日曆",
        "ecTimezone": "美東時間",
        "ecFootnote": "來源：Federal Reserve · BLS · BEA · 日期可能變更"
    }
}

updated = 0
for locale, new_keys in NEW_KEYS.items():
    path = os.path.join(MESSAGES_DIR, f"{locale}.json")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    intel = data.get("intelligence", {})
    for k, v in new_keys.items():
        intel[k] = v
    data["intelligence"] = intel
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    updated += 1
    print(f"  {locale}: +{len(new_keys)} keys")

print(f"\nTotal: {updated} files updated, {len(list(NEW_KEYS.values())[0])} keys each = {updated * len(list(NEW_KEYS.values())[0])} total")
