#!/usr/bin/env python3
"""Add 'macro' i18n namespace to all 16 messages/*.json files for MacroIndicatorsTab."""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).parent.parent / "messages"

TRANSLATIONS: dict[str, dict] = {
  "ko": {
    # FedWatch
    "fwLoading": "FedWatch 로딩중...",
    "fwTitle": "CME FedWatch — FOMC 금리 전망",
    "fwDesc": "각 회의별 시장이 예상하는 금리 결정 확률",
    "fwCurrentRate": "현재 기준금리",
    "fwYearEnd": "연말 예상",
    "fwBpCut": "-{n}bp 인하",
    "fwExpRate": "예상금리",
    "fwHold": "동결",
    "fwCutDominant": "인하 우세 ({pct}%)",
    "fwHoldDominant": "동결 우세 ({pct}%)",
    "fwMixed": "혼재",
    "fwFootnote": "💡 확률은 Fed Funds 선물 가격 기반 시장 컨센서스 (CME FedWatch 스타일)",
    "fwBasis": "기준: {date}",
    # MacroRiskSignal
    "mrRiskOnLabel": "리스크 온 (Risk-On)",
    "mrRiskOnDesc": "신용 건전·소비 낙관·금리 정상화 → 위험자산 선호",
    "mrNeutralLabel": "중립 (Neutral)",
    "mrNeutralDesc": "신용 안정이나 소비 심리 혼재 → 방향성 불명확",
    "mrRiskOffLabel": "리스크 오프 (Risk-Off)",
    "mrRiskOffDesc": "신용 스트레스·소비 위축·금리 역전 → 안전자산 선호",
    "mrYieldCurve": "금리 곡선",
    "mrInverted": "역전 ⚠",
    "mrNormal": "정상",
    "mrSubtitle": "신용·소비·금리 종합 신호",
    # SURPRISE_BADGE
    "sbBeat": "긍정 서프라이즈 ▲",
    "sbMiss": "부정 서프라이즈 ▼",
    "sbInline": "예상 부합 →",
    "sbPending": "발표 대기",
    # RATE_BADGE
    "rbHawkish": "🦅 매파 (긴축)",
    "rbDovish": "🕊️ 비둘기파 (완화)",
    "rbNeutral": "⚖️ 중립",
    # CAT_LABELS
    "catInflation": "물가",
    "catEmployment": "고용",
    "catGrowth": "경기",
    "catMonetary": "통화정책",
    "catTrade": "무역",
    "catCredit": "신용",
    # SectorPE
    "spTitle": "섹터 ETF (가격 · 등락률 · YTD)",
    "spColSector": "섹터 ETF",
    "spColPrice": "가격",
    "spColChange": "등락률",
    "spFootnote": "출처: Yahoo Finance v8 · SPDR 섹터 ETF · 4h 캐시",
    # MacroIndicatorsTab main
    "miLoading": "경제지표 로딩중...",
    "miTitle": "금리·시장을 움직이는 핵심 경제지표",
    "miDesc": "각 지표 발표가 주식·채권·달러·금에 어떤 연쇄 영향(cascade)을 미치는지 보여줍니다.",
    "miLaymanHint": "💡 버튼을 누르면 쉬운 설명을 볼 수 있어요.",
    "miYieldTitle": "미 국채 수익률 곡선 (Yield Curve)",
    "miYieldInverted": "⚠️ 역전 — 침체 선행지표",
    "miUpcomingTitle": "다가오는 경제지표 발표",
    "miToday": "오늘",
    "miTomorrow": "내일",
    "miDaysLater": "{days}일 후",
    "miConsensus": "컨센서스 {value}{unit}",
    "miIndicatorsTitle": "주요 경제지표 발표 결과 & Cascade 분석",
    "miClickHint": "클릭 → cascade · 💡 클릭 → 쉬운 설명",
    "miActual": "실제",
    "miEstimate": "예상",
    "miCascadeExpand": "Cascade 영향 보기",
    "miCascadeCollapse": "Cascade 영향 접기",
    "miLaymanExpand": "쉬운 설명 보기",
    "miLaymanCollapse": "쉬운 설명 접기",
    "miReleaseDate": "발표일",
    "miNextRelease": "다음 발표",
    "miCascadeTitle": "이 발표가 시장에 미치는 연쇄 영향",
    "miMagStrong": "강",
    "miMagMedium": "중",
    "miMagWeak": "약",
    "miNoCascade": "예상에 부합한 결과 — 시장이 이미 예상했던 내용이라 큰 변동이 없어요.",
    # LaymanBox
    "lbWhat": "이 지표가 뭔가요?",
    "lbWhy": "왜 중요한가요?",
    # LAYMAN — CPI
    "lCpiWhat": "마트·식당 등 우리가 매일 사는 물건들의 가격이 1년 전보다 얼마나 올랐는지 보여줍니다.",
    "lCpiWhy": "Fed(미국 중앙은행)가 금리를 올릴지 내릴지 결정하는 핵심 지표예요.",
    "lCpiGood": "예상보다 낮으면 → 물가가 안정 → 금리 인하 기대 → 주식 상승 가능성",
    "lCpiBad": "예상보다 높으면 → 물가 과열 → 금리 인상 → 주식·채권 동반 하락 위험",
    # LAYMAN — PCE
    "lPceWhat": "CPI와 비슷하지만 Fed가 더 중요하게 보는 물가 지표예요. 사람들이 실제로 얼마나 쓰고 있는지 더 정확히 잡아냅니다.",
    "lPceWhy": "Fed 의장이 공개적으로 \"가장 선호하는 인플레 지표\"라고 언급했어요.",
    "lPceGood": "예상보다 낮으면 → 금리 인하 시기 앞당겨질 수 있음",
    "lPceBad": "예상보다 높으면 → 금리 인하 늦어짐 → 성장주 불리",
    # LAYMAN — NFP
    "lNfpWhat": "지난 한 달 동안 미국에서 일자리가 몇 개 생겼는지 세는 지표예요. (농업 제외)",
    "lNfpWhy": "일자리 = 경기의 온도계. 많이 늘면 경기 좋다는 신호. Fed도 이 숫자 보고 금리 결정해요.",
    "lNfpGood": "예상보다 낮으면 → 경기 둔화 → Fed 인하 압박 → 채권 상승",
    "lNfpBad": "예상보다 높으면 → 경기 과열 → Fed 인하 어려워짐 → 성장주 단기 압박",
    # LAYMAN — FOMC
    "lFomcWhat": "Fed(미국 중앙은행)가 기준금리를 올릴지·내릴지·유지할지 결정하는 회의예요. 1년에 8번 열려요.",
    "lFomcWhy": "전 세계 모든 자산 가격에 직접 영향을 미치는 가장 중요한 이벤트예요.",
    "lFomcGood": "예상보다 비둘기(인하/동결) → 주식·암호화폐·금 일제히 상승",
    "lFomcBad": "예상보다 매파(인상/강경) → 주식 급락, 달러 급등, EM 자금 이탈",
    # LAYMAN — GDP
    "lGdpWhat": "미국 경제 전체가 한 분기에 얼마나 성장했는지 보여주는 숫자예요. 연율로 환산해서 발표돼요.",
    "lGdpWhy": "경제의 건강상태 성적표. 2% 이상이면 건강, 마이너스 두 분기 연속이면 공식 침체예요.",
    "lGdpGood": "예상보다 높으면 → 기업 실적 기대↑ → 주식 긍정",
    "lGdpBad": "예상보다 낮으면 → 침체 우려 → 안전자산(금·채권) 매수",
    # LAYMAN — ISM
    "lIsmWhat": "제조업체 구매 담당자들에게 \"지금 경기 좋아요?\"라고 물어본 설문 지표예요. 50 이상이면 성장, 이하면 수축이에요.",
    "lIsmWhy": "실제 경기보다 약 2~3개월 앞서 움직이는 선행 지표로 유명해요.",
    "lIsmGood": "50 이상 + 예상 상회 → 제조업 회복 → 산업주·원자재 상승",
    "lIsmBad": "50 이하 + 예상 하회 → 제조업 침체 → 경기민감주 하락",
    # LAYMAN — Retail
    "lRetailWhat": "미국 소비자들이 지난 한 달 동안 쇼핑에 얼마나 썼는지 집계한 지표예요. 미국 GDP의 70%가 소비예요.",
    "lRetailWhy": "소비가 줄면 기업 매출 → 실적 → 주가에 직접 영향을 미쳐요.",
    "lRetailGood": "예상보다 높으면 → 소비 강세 → 리테일·소비재 주식 상승",
    "lRetailBad": "예상보다 낮으면 → 소비 둔화 → 경기침체 우려",
    # LAYMAN — PPI
    "lPpiWhat": "기업이 물건을 만들 때 드는 원재료·부품 비용이 얼마나 올랐는지 보여줘요. CPI보다 1~2개월 앞서서 나와요.",
    "lPpiWhy": "PPI가 오르면 → 기업이 가격 올림 → 나중에 CPI도 오를 수 있어요. CPI 예측 지표로 활용해요.",
    "lPpiGood": "예상보다 낮으면 → 원가 부담 완화 → 기업 마진 개선 기대",
    "lPpiBad": "예상보다 높으면 → 향후 CPI 상승 예고 → 긴축 우려",
    # LAYMAN — UNRATE
    "lUnrateWhat": "일하고 싶은데 일자리를 못 찾은 사람이 전체 노동자의 몇 %인지 보여줘요.",
    "lUnrateWhy": "Fed의 두 가지 임무 중 하나가 \"완전 고용\"이에요. 실업률이 너무 낮으면 임금 인플레 우려.",
    "lUnrateGood": "높아지면 → 경기 둔화 → Fed 인하 압박",
    "lUnrateBad": "너무 낮으면 → 임금 상승 → 인플레 → 금리 인상 위험",
    # LAYMAN — IG Spread
    "lIgWhat": "투자등급(IG) 회사채 금리에서 미국 국채 금리를 뺀 차이예요. 기업이 돈 빌릴 때 내야 하는 \"위험 프리미엄\"이에요.",
    "lIgWhy": "스프레드가 넓어질수록 신용 위기 가능성↑. 1.5% 넘으면 경보, 2%+면 위기 수준이에요.",
    "lIgGood": "스프레드 축소(낮아짐) → 기업 자금 조달 용이 → 투자·고용 확대",
    "lIgBad": "스프레드 확대(높아짐) → 기업 대출 비용↑ → 투자 위축 → 주가 하락 선행 신호",
    # LAYMAN — HY Spread
    "lHyWhat": "고수익채(정크본드) 금리에서 미국 국채 금리를 뺀 차이예요. 신용 위험이 가장 높은 기업들의 \"공포 지수\"예요.",
    "lHyWhy": "5% 초과 = 경기침체 경보. 역사적으로 대공황급 위기 때 10%+까지 올랐어요.",
    "lHyGood": "스프레드 축소 → 위험 선호 복귀 → 주식·하이일드 채권 동반 강세",
    "lHyBad": "5% 이상 → 신용 시장 패닉 → 기업 부도 증가 → 주식 급락 동반",
  },
  "en": {
    "fwLoading": "Loading FedWatch...",
    "fwTitle": "CME FedWatch — FOMC Rate Outlook",
    "fwDesc": "Market-implied probability of rate decisions at each meeting",
    "fwCurrentRate": "Current Fed Funds Rate",
    "fwYearEnd": "Year-End Implied",
    "fwBpCut": "-{n}bp cut",
    "fwExpRate": "Implied Rate",
    "fwHold": "Hold",
    "fwCutDominant": "Cut dominant ({pct}%)",
    "fwHoldDominant": "Hold dominant ({pct}%)",
    "fwMixed": "Mixed",
    "fwFootnote": "💡 Probabilities derived from Fed Funds futures — CME FedWatch methodology",
    "fwBasis": "As of: {date}",
    "mrRiskOnLabel": "Risk-On",
    "mrRiskOnDesc": "Healthy credit · optimistic consumers · normalized yield curve → risk assets favored",
    "mrNeutralLabel": "Neutral",
    "mrNeutralDesc": "Credit stable but mixed sentiment → direction unclear",
    "mrRiskOffLabel": "Risk-Off",
    "mrRiskOffDesc": "Credit stress · weak consumption · inverted yield curve → safe-haven assets favored",
    "mrYieldCurve": "Yield Curve",
    "mrInverted": "Inverted ⚠",
    "mrNormal": "Normal",
    "mrSubtitle": "Credit · Consumer · Rates composite signal",
    "sbBeat": "Positive Surprise ▲",
    "sbMiss": "Negative Surprise ▼",
    "sbInline": "In-Line →",
    "sbPending": "Pending",
    "rbHawkish": "🦅 Hawkish (Tightening)",
    "rbDovish": "🕊️ Dovish (Easing)",
    "rbNeutral": "⚖️ Neutral",
    "catInflation": "Inflation",
    "catEmployment": "Employment",
    "catGrowth": "Growth",
    "catMonetary": "Monetary Policy",
    "catTrade": "Trade",
    "catCredit": "Credit",
    "spTitle": "Sector ETFs (Price · Change · YTD)",
    "spColSector": "Sector ETF",
    "spColPrice": "Price",
    "spColChange": "Change",
    "spFootnote": "Source: Yahoo Finance v8 · SPDR Sector ETFs · 4h cache",
    "miLoading": "Loading economic indicators...",
    "miTitle": "Key Economic Indicators Moving Rates & Markets",
    "miDesc": "Shows how each data release creates cascading effects on stocks, bonds, the dollar, and gold.",
    "miLaymanHint": "💡 Tap the button for a plain-English explanation.",
    "miYieldTitle": "U.S. Treasury Yield Curve",
    "miYieldInverted": "⚠️ Inverted — Recession leading indicator",
    "miUpcomingTitle": "Upcoming Economic Releases",
    "miToday": "Today",
    "miTomorrow": "Tomorrow",
    "miDaysLater": "In {days}d",
    "miConsensus": "Consensus {value}{unit}",
    "miIndicatorsTitle": "Economic Releases & Cascade Analysis",
    "miClickHint": "Click → cascade · 💡 Click → plain explanation",
    "miActual": "Actual",
    "miEstimate": "Est.",
    "miCascadeExpand": "Show Cascade",
    "miCascadeCollapse": "Hide Cascade",
    "miLaymanExpand": "Plain English",
    "miLaymanCollapse": "Hide Explanation",
    "miReleaseDate": "Released",
    "miNextRelease": "Next release",
    "miCascadeTitle": "Market cascade from this release",
    "miMagStrong": "Strong",
    "miMagMedium": "Mod",
    "miMagWeak": "Weak",
    "miNoCascade": "In-line result — market already priced this in, no major reaction expected.",
    "lbWhat": "What is this indicator?",
    "lbWhy": "Why does it matter?",
    "lCpiWhat": "Shows how much prices of everyday goods — groceries, restaurants, etc. — have risen compared to a year ago.",
    "lCpiWhy": "The Fed's key gauge for deciding whether to raise or cut interest rates.",
    "lCpiGood": "Below forecast → price stability → rate cut hopes → stocks can rally",
    "lCpiBad": "Above forecast → overheating inflation → rate hikes → stocks & bonds fall together",
    "lPceWhat": "Similar to CPI but the Fed's preferred inflation measure. Captures how much people are actually spending more accurately.",
    "lPceWhy": "The Fed Chair has publicly called it \"our preferred inflation gauge.\"",
    "lPceGood": "Below forecast → rate cuts may come sooner",
    "lPceBad": "Above forecast → rate cuts delayed → growth stocks under pressure",
    "lNfpWhat": "Counts how many new jobs the U.S. economy added last month (excluding farming).",
    "lNfpWhy": "Jobs are the economy's thermometer. Strong gains = healthy economy. The Fed watches this number closely.",
    "lNfpGood": "Below forecast → slowdown → Fed cut pressure → bonds rally",
    "lNfpBad": "Above forecast → overheating → Fed cuts harder to justify → growth stocks short-term pressure",
    "lFomcWhat": "The Fed's meeting where they decide to raise, cut, or hold interest rates. Held 8 times a year.",
    "lFomcWhy": "The single most market-moving event — directly impacts every asset class in the world.",
    "lFomcGood": "More dovish than expected (cut/hold) → stocks, crypto, gold rally together",
    "lFomcBad": "More hawkish than expected (hike/tough) → stocks plunge, dollar surges, EM capital flight",
    "lGdpWhat": "Measures how much the entire U.S. economy grew in a quarter, expressed as an annualized rate.",
    "lGdpWhy": "The economy's report card. Above 2% = healthy. Two negative quarters in a row = official recession.",
    "lGdpGood": "Above forecast → stronger earnings expectations → positive for stocks",
    "lGdpBad": "Below forecast → recession fears → buy safe havens (gold, bonds)",
    "lIsmWhat": "Surveys purchasing managers at manufacturers: \"Is business getting better?\" Above 50 = expansion, below = contraction.",
    "lIsmWhy": "Famous leading indicator that tends to move 2–3 months ahead of the actual economy.",
    "lIsmGood": "Above 50 + beats expectations → manufacturing recovery → industrials & commodities rise",
    "lIsmBad": "Below 50 + misses → manufacturing contraction → cyclical stocks fall",
    "lRetailWhat": "Tracks how much U.S. consumers spent shopping last month. Consumer spending = ~70% of U.S. GDP.",
    "lRetailWhy": "Consumer spending directly feeds into corporate revenues → earnings → stock prices.",
    "lRetailGood": "Above forecast → strong consumption → retail & consumer stocks rally",
    "lRetailBad": "Below forecast → consumption slowing → recession concerns",
    "lPpiWhat": "Measures how much raw material and parts costs for manufacturers have risen. Comes out 1–2 months before CPI.",
    "lPpiWhy": "PPI rises → companies raise prices → CPI rises later. Used as a CPI leading indicator.",
    "lPpiGood": "Below forecast → cost pressures easing → better corporate margins expected",
    "lPpiBad": "Above forecast → signals future CPI spike → tightening fears",
    "lUnrateWhat": "The percentage of workers who want a job but can't find one.",
    "lUnrateWhy": "\"Maximum employment\" is one of the Fed's two mandates. Very low unemployment → wage inflation risk.",
    "lUnrateGood": "Rising → economic slowdown → Fed cut pressure",
    "lUnrateBad": "Too low → wage pressure → inflation → rate hike risk",
    "lIgWhat": "The gap between investment-grade corporate bond yields and U.S. Treasury yields — the 'risk premium' companies pay to borrow.",
    "lIgWhy": "Wider spread = higher credit stress. Above 1.5% = alert, above 2% = crisis territory.",
    "lIgGood": "Spread narrowing → cheaper corporate borrowing → investment & hiring expand",
    "lIgBad": "Spread widening → higher borrowing costs → investment contracts → leads stocks lower",
    "lHyWhat": "The gap between high-yield (junk bond) yields and U.S. Treasuries — the \"fear gauge\" for the riskiest borrowers.",
    "lHyWhy": "Above 5% = recession warning. Historically peaked above 10% during major crises.",
    "lHyGood": "Spread narrowing → risk appetite returning → stocks & high-yield bonds rally together",
    "lHyBad": "Above 5% → credit market panic → corporate defaults rise → stocks plunge",
  },
  "ja": {
    "fwLoading": "FedWatch 読み込み中...",
    "fwTitle": "CME FedWatch — FOMC 金利見通し",
    "fwDesc": "各会合での市場予想金利決定確率",
    "fwCurrentRate": "現在の政策金利",
    "fwYearEnd": "年末予想",
    "fwBpCut": "-{n}bp 利下げ",
    "fwExpRate": "予想金利",
    "fwHold": "据え置き",
    "fwCutDominant": "利下げ優勢 ({pct}%)",
    "fwHoldDominant": "据え置き優勢 ({pct}%)",
    "fwMixed": "混在",
    "fwFootnote": "💡 確率はFed Funds先物価格に基づく市場コンセンサス",
    "fwBasis": "基準: {date}",
    "mrRiskOnLabel": "リスクオン",
    "mrRiskOnDesc": "信用健全・消費楽観・金利正常化 → リスク資産選好",
    "mrNeutralLabel": "中立",
    "mrNeutralDesc": "信用安定だが消費心理混在 → 方向感不明確",
    "mrRiskOffLabel": "リスクオフ",
    "mrRiskOffDesc": "信用ストレス・消費低迷・長短逆転 → 安全資産選好",
    "mrYieldCurve": "イールドカーブ",
    "mrInverted": "逆転 ⚠",
    "mrNormal": "正常",
    "mrSubtitle": "信用・消費・金利総合シグナル",
    "sbBeat": "ポジティブサプライズ ▲",
    "sbMiss": "ネガティブサプライズ ▼",
    "sbInline": "予想通り →",
    "sbPending": "発表待ち",
    "rbHawkish": "🦅 タカ派 (引き締め)",
    "rbDovish": "🕊️ ハト派 (緩和)",
    "rbNeutral": "⚖️ 中立",
    "catInflation": "物価",
    "catEmployment": "雇用",
    "catGrowth": "景気",
    "catMonetary": "金融政策",
    "catTrade": "貿易",
    "catCredit": "信用",
    "spTitle": "セクターETF (価格・騰落率・YTD)",
    "spColSector": "セクターETF",
    "spColPrice": "価格",
    "spColChange": "騰落率",
    "spFootnote": "出所: Yahoo Finance v8 · SPDR セクターETF · 4hキャッシュ",
    "miLoading": "経済指標読み込み中...",
    "miTitle": "金利・市場を動かす主要経済指標",
    "miDesc": "各指標の発表が株式・債券・ドル・金にどう連鎖影響するか示します。",
    "miLaymanHint": "💡 ボタンを押すとわかりやすい解説が見られます。",
    "miYieldTitle": "米国債イールドカーブ",
    "miYieldInverted": "⚠️ 逆転 — 景気後退の先行指標",
    "miUpcomingTitle": "今後の経済指標発表",
    "miToday": "今日",
    "miTomorrow": "明日",
    "miDaysLater": "{days}日後",
    "miConsensus": "予想 {value}{unit}",
    "miIndicatorsTitle": "経済指標発表結果 & カスケード分析",
    "miClickHint": "クリック → cascade · 💡 クリック → 解説",
    "miActual": "実績",
    "miEstimate": "予想",
    "miCascadeExpand": "カスケード影響を表示",
    "miCascadeCollapse": "カスケード影響を閉じる",
    "miLaymanExpand": "解説を表示",
    "miLaymanCollapse": "解説を閉じる",
    "miReleaseDate": "発表日",
    "miNextRelease": "次回発表",
    "miCascadeTitle": "この発表が市場に与える連鎖影響",
    "miMagStrong": "強",
    "miMagMedium": "中",
    "miMagWeak": "弱",
    "miNoCascade": "予想通りの結果 — 市場はすでに織り込み済みで大きな変動なし。",
    "lbWhat": "この指標とは？",
    "lbWhy": "なぜ重要？",
    "lCpiWhat": "スーパーやレストランなど日常的に購入するものの価格が1年前より何%上がったかを示します。",
    "lCpiWhy": "Fedが利上げ・利下げを決める際の核心指標です。",
    "lCpiGood": "予想より低い → 物価安定 → 利下げ期待 → 株価上昇の可能性",
    "lCpiBad": "予想より高い → 物価過熱 → 利上げ → 株・債券共に下落リスク",
    "lPceWhat": "CPIと似ていますが、Fedがより重視する物価指標。実際の消費支出をより正確に捉えます。",
    "lPceWhy": "Fed議長が「最も重視するインフレ指標」と公言しています。",
    "lPceGood": "予想より低い → 利下げ時期が早まる可能性",
    "lPceBad": "予想より高い → 利下げ先送り → グロース株に不利",
    "lNfpWhat": "先月、米国で農業を除く雇用者数が何人増えたかを集計した指標です。",
    "lNfpWhy": "雇用=景気の体温計。増加が多いほど景気良好のサイン。Fedもこの数字を見て金利を決めます。",
    "lNfpGood": "予想より低い → 景気減速 → Fed利下げ圧力 → 債券上昇",
    "lNfpBad": "予想より高い → 景気過熱 → Fed利下げ困難 → グロース株に短期的な圧力",
    "lFomcWhat": "Fedが政策金利を上げるか・下げるか・維持するかを決める会合。年8回開催。",
    "lFomcWhy": "全世界の資産価格に直接影響する最重要イベントです。",
    "lFomcGood": "予想よりハト派（利下げ/据え置き）→ 株・仮想通貨・金が一斉上昇",
    "lFomcBad": "予想よりタカ派（利上げ/強硬）→ 株急落、ドル急騰、新興国資金流出",
    "lGdpWhat": "米国経済全体が1四半期にどれだけ成長したかを示す数字。年率換算で発表されます。",
    "lGdpWhy": "経済の健康状態の通信簿。2%以上は健全、2四半期連続マイナスは公式景気後退。",
    "lGdpGood": "予想より高い → 企業業績期待↑ → 株式にポジティブ",
    "lGdpBad": "予想より低い → 景気後退懸念 → 安全資産（金・債券）買い",
    "lIsmWhat": "製造業の購買担当者に「今、景気は良くなってますか？」と聞いたアンケート指標。50以上が拡張、以下が収縮。",
    "lIsmWhy": "実際の景気より2〜3ヶ月先行すると言われる先行指標として有名。",
    "lIsmGood": "50以上＋予想上回り → 製造業回復 → 産業株・原材料上昇",
    "lIsmBad": "50以下＋予想下回り → 製造業縮小 → 景気敏感株下落",
    "lRetailWhat": "米国消費者が先月、買い物にどれだけ使ったかを集計した指標。米GDPの70%が消費です。",
    "lRetailWhy": "消費が減ると企業売上→業績→株価に直接影響します。",
    "lRetailGood": "予想より高い → 消費強い → 小売・消費財株上昇",
    "lRetailBad": "予想より低い → 消費鈍化 → 景気後退懸念",
    "lPpiWhat": "企業が製品を作る際の原材料・部品コストがどれだけ上がったかを示します。CPIより1〜2ヶ月早く発表されます。",
    "lPpiWhy": "PPI上昇→企業が値上げ→後にCPIも上昇。CPI予測指標として活用されます。",
    "lPpiGood": "予想より低い → コスト負担軽減 → 企業マージン改善期待",
    "lPpiBad": "予想より高い → 今後のCPI上昇を予告 → 引き締め懸念",
    "lUnrateWhat": "働きたいのに仕事が見つからない人が全労働者の何%かを示します。",
    "lUnrateWhy": "Fedの使命の一つが「完全雇用」。失業率が低すぎると賃金インフレのリスク。",
    "lUnrateGood": "上昇 → 景気減速 → Fed利下げ圧力",
    "lUnrateBad": "低すぎる → 賃金上昇 → インフレ → 利上げリスク",
    "lIgWhat": "投資適格債の利回りから米国債利回りを引いた差。企業が借入に払う「リスクプレミアム」です。",
    "lIgWhy": "スプレッドが広がるほど信用危機の可能性が高い。1.5%超で警戒、2%超で危機水準。",
    "lIgGood": "スプレッド縮小 → 企業資金調達が容易 → 投資・雇用拡大",
    "lIgBad": "スプレッド拡大 → 借入コスト上昇 → 投資萎縮 → 株価下落の先行シグナル",
    "lHyWhat": "ハイイールド債（ジャンク債）の利回りから米国債を引いた差。最もリスクの高い企業の「恐怖指数」。",
    "lHyWhy": "5%超=景気後退警告。歴史的に大恐慌級の危機では10%以上まで上昇。",
    "lHyGood": "スプレッド縮小 → リスク選好回帰 → 株・ハイイールド債が共に上昇",
    "lHyBad": "5%以上 → 信用市場パニック → 企業倒産増加 → 株急落",
  },
  "zh-CN": {
    "fwLoading": "加载 FedWatch 中...",
    "fwTitle": "CME FedWatch — FOMC 利率展望",
    "fwDesc": "市场隐含的每次会议利率决策概率",
    "fwCurrentRate": "当前联邦基金利率",
    "fwYearEnd": "年末预期",
    "fwBpCut": "降息 {n}bp",
    "fwExpRate": "隐含利率",
    "fwHold": "维持不变",
    "fwCutDominant": "降息主导 ({pct}%)",
    "fwHoldDominant": "维持主导 ({pct}%)",
    "fwMixed": "混合",
    "fwFootnote": "💡 概率基于联邦基金期货价格（CME FedWatch方法）",
    "fwBasis": "基准: {date}",
    "mrRiskOnLabel": "风险偏好 (Risk-On)",
    "mrRiskOnDesc": "信用健康·消费乐观·收益率曲线正常 → 偏好风险资产",
    "mrNeutralLabel": "中性",
    "mrNeutralDesc": "信用稳定但消费情绪混合 → 方向不明",
    "mrRiskOffLabel": "避险 (Risk-Off)",
    "mrRiskOffDesc": "信用压力·消费疲软·收益率曲线倒挂 → 偏好避险资产",
    "mrYieldCurve": "收益率曲线",
    "mrInverted": "倒挂 ⚠",
    "mrNormal": "正常",
    "mrSubtitle": "信用·消费·利率综合信号",
    "sbBeat": "超预期 ▲",
    "sbMiss": "低于预期 ▼",
    "sbInline": "符合预期 →",
    "sbPending": "等待发布",
    "rbHawkish": "🦅 鹰派（收紧）",
    "rbDovish": "🕊️ 鸽派（宽松）",
    "rbNeutral": "⚖️ 中立",
    "catInflation": "通胀",
    "catEmployment": "就业",
    "catGrowth": "经济增长",
    "catMonetary": "货币政策",
    "catTrade": "贸易",
    "catCredit": "信用",
    "spTitle": "板块ETF（价格·涨跌幅·YTD）",
    "spColSector": "板块ETF",
    "spColPrice": "价格",
    "spColChange": "涨跌幅",
    "spFootnote": "来源: Yahoo Finance v8 · SPDR板块ETF · 4h缓存",
    "miLoading": "加载经济指标中...",
    "miTitle": "影响利率与市场的核心经济指标",
    "miDesc": "展示每项指标发布如何对股票、债券、美元、黄金产生连锁影响。",
    "miLaymanHint": "💡 点击按钮查看通俗解释。",
    "miYieldTitle": "美国国债收益率曲线",
    "miYieldInverted": "⚠️ 倒挂 — 经济衰退领先指标",
    "miUpcomingTitle": "即将发布的经济数据",
    "miToday": "今天",
    "miTomorrow": "明天",
    "miDaysLater": "{days}天后",
    "miConsensus": "预期 {value}{unit}",
    "miIndicatorsTitle": "经济数据发布结果 & 连锁分析",
    "miClickHint": "点击 → 连锁影响 · 💡 点击 → 通俗解释",
    "miActual": "实际",
    "miEstimate": "预期",
    "miCascadeExpand": "查看连锁影响",
    "miCascadeCollapse": "收起连锁影响",
    "miLaymanExpand": "查看解释",
    "miLaymanCollapse": "收起解释",
    "miReleaseDate": "发布日",
    "miNextRelease": "下次发布",
    "miCascadeTitle": "此次发布对市场的连锁影响",
    "miMagStrong": "强",
    "miMagMedium": "中",
    "miMagWeak": "弱",
    "miNoCascade": "符合预期的结果 — 市场已提前消化，预计不会出现大幅波动。",
    "lbWhat": "这个指标是什么？",
    "lbWhy": "为什么重要？",
    "lCpiWhat": "显示我们每天购买的商品（超市、餐厅等）价格比一年前上涨了多少。",
    "lCpiWhy": "美联储决定加息或降息的核心指标。",
    "lCpiGood": "低于预期 → 物价稳定 → 降息预期 → 股市可能上涨",
    "lCpiBad": "高于预期 → 物价过热 → 加息 → 股票和债券同步下跌风险",
    "lPceWhat": "与CPI类似，但美联储更重视这个指标。更准确地反映人们的实际消费支出。",
    "lPceWhy": "美联储主席公开表示这是「最偏好的通胀指标」。",
    "lPceGood": "低于预期 → 降息时机可能提前",
    "lPceBad": "高于预期 → 降息推迟 → 成长股不利",
    "lNfpWhat": "统计上个月美国新增了多少就业岗位（不含农业）。",
    "lNfpWhy": "就业=经济温度计。大量增加意味着经济良好。美联储也根据此数据决定利率。",
    "lNfpGood": "低于预期 → 经济放缓 → 美联储降息压力 → 债券上涨",
    "lNfpBad": "高于预期 → 经济过热 → 美联储难以降息 → 成长股短期压力",
    "lFomcWhat": "美联储决定提高、降低或维持基准利率的会议。每年召开8次。",
    "lFomcWhy": "直接影响全球所有资产价格的最重要事件。",
    "lFomcGood": "比预期更鸽派（降息/维持）→ 股票、加密货币、黄金齐涨",
    "lFomcBad": "比预期更鹰派（加息/强硬）→ 股市暴跌、美元急升、新兴市场资金外流",
    "lGdpWhat": "显示美国整体经济一个季度增长了多少，以年化率表示。",
    "lGdpWhy": "经济健康状况的成绩单。2%以上为健康，连续两个季度负增长为官方衰退。",
    "lGdpGood": "高于预期 → 企业盈利预期↑ → 对股市利好",
    "lGdpBad": "低于预期 → 衰退担忧 → 买入避险资产（黄金·债券）",
    "lIsmWhat": "向制造业采购经理询问「现在景气好吗？」的调查指标。50以上为扩张，以下为收缩。",
    "lIsmWhy": "比实际经济领先约2-3个月的著名先行指标。",
    "lIsmGood": "50以上+超预期 → 制造业复苏 → 工业股、大宗商品上涨",
    "lIsmBad": "50以下+低于预期 → 制造业萎缩 → 周期股下跌",
    "lRetailWhat": "统计美国消费者上个月购物花了多少钱。消费占美国GDP的70%。",
    "lRetailWhy": "消费减少会直接影响企业营收→业绩→股价。",
    "lRetailGood": "高于预期 → 消费强劲 → 零售·消费品股票上涨",
    "lRetailBad": "低于预期 → 消费放缓 → 经济衰退担忧",
    "lPpiWhat": "显示企业制造产品时原材料和零部件成本上涨了多少。比CPI提前1-2个月发布。",
    "lPpiWhy": "PPI上涨→企业提价→后来CPI也会上涨。用作CPI预测指标。",
    "lPpiGood": "低于预期 → 成本压力缓解 → 企业利润率改善预期",
    "lPpiBad": "高于预期 → 预示未来CPI上涨 → 紧缩担忧",
    "lUnrateWhat": "显示想工作却找不到工作的人占全体劳动者的比例。",
    "lUnrateWhy": "美联储的使命之一是「充分就业」。失业率太低会有工资通胀风险。",
    "lUnrateGood": "上升 → 经济放缓 → 美联储降息压力",
    "lUnrateBad": "过低 → 工资上涨 → 通胀 → 加息风险",
    "lIgWhat": "投资级公司债券收益率与美国国债收益率之差。企业借款需要支付的「风险溢价」。",
    "lIgWhy": "价差越大信用危机可能性越高。超过1.5%为警报，超过2%为危机水平。",
    "lIgGood": "价差收窄 → 企业融资便利 → 投资和就业扩大",
    "lIgBad": "价差扩大 → 企业借贷成本上升 → 投资萎缩 → 股价下跌的领先信号",
    "lHyWhat": "高收益债（垃圾债）收益率与美国国债之差。信用风险最高企业的「恐慌指数」。",
    "lHyWhy": "超过5%=经济衰退警报。历史上大萧条级危机时曾超过10%。",
    "lHyGood": "价差收窄 → 风险偏好回归 → 股票和高收益债券同步走强",
    "lHyBad": "5%以上 → 信用市场恐慌 → 企业违约增加 → 股市暴跌",
  },
}

# For the remaining 12 languages, use English text as placeholder
# (better than showing raw key names)
REMAINING_LANGS = ["zh-TW", "es", "fr", "de", "pt", "ru", "ar", "hi", "id", "th", "tr", "vi"]

# zh-TW is close to zh-CN — provide proper Traditional Chinese
ZH_TW_OVERRIDES = {
    "fwLoading": "載入 FedWatch 中...",
    "fwTitle": "CME FedWatch — FOMC 利率展望",
    "fwDesc": "市場隱含的每次會議利率決策概率",
    "fwCurrentRate": "當前聯邦基金利率",
    "fwYearEnd": "年末預期",
    "fwBpCut": "降息 {n}bp",
    "fwExpRate": "隱含利率",
    "fwHold": "維持不變",
    "fwCutDominant": "降息主導 ({pct}%)",
    "fwHoldDominant": "維持主導 ({pct}%)",
    "fwMixed": "混合",
    "fwFootnote": "💡 概率基於聯邦基金期貨價格（CME FedWatch方法）",
    "fwBasis": "基準: {date}",
    "mrRiskOnLabel": "風險偏好 (Risk-On)",
    "mrRiskOnDesc": "信用健康·消費樂觀·收益率曲線正常 → 偏好風險資產",
    "mrNeutralLabel": "中性",
    "mrNeutralDesc": "信用穩定但消費情緒混合 → 方向不明",
    "mrRiskOffLabel": "避險 (Risk-Off)",
    "mrRiskOffDesc": "信用壓力·消費疲軟·收益率曲線倒掛 → 偏好避險資產",
    "mrYieldCurve": "收益率曲線",
    "mrInverted": "倒掛 ⚠",
    "mrNormal": "正常",
    "mrSubtitle": "信用·消費·利率綜合訊號",
    "sbBeat": "超預期 ▲",
    "sbMiss": "低於預期 ▼",
    "sbInline": "符合預期 →",
    "sbPending": "等待發布",
    "rbHawkish": "🦅 鷹派（收緊）",
    "rbDovish": "🕊️ 鴿派（寬鬆）",
    "rbNeutral": "⚖️ 中立",
    "catInflation": "通膨",
    "catEmployment": "就業",
    "catGrowth": "經濟成長",
    "catMonetary": "貨幣政策",
    "catTrade": "貿易",
    "catCredit": "信用",
    "spTitle": "板塊ETF（價格·漲跌幅·YTD）",
    "spColSector": "板塊ETF",
    "spColPrice": "價格",
    "spColChange": "漲跌幅",
    "spFootnote": "來源: Yahoo Finance v8 · SPDR板塊ETF · 4h緩存",
    "miLoading": "載入經濟指標中...",
    "miTitle": "影響利率與市場的核心經濟指標",
    "miDesc": "展示每項指標發布如何對股票、債券、美元、黃金產生連鎖影響。",
    "miLaymanHint": "💡 點擊按鈕查看通俗解釋。",
    "miYieldTitle": "美國國債收益率曲線",
    "miYieldInverted": "⚠️ 倒掛 — 經濟衰退領先指標",
    "miUpcomingTitle": "即將發布的經濟數據",
    "miToday": "今天",
    "miTomorrow": "明天",
    "miDaysLater": "{days}天後",
    "miConsensus": "預期 {value}{unit}",
    "miIndicatorsTitle": "經濟數據發布結果 & 連鎖分析",
    "miClickHint": "點擊 → 連鎖影響 · 💡 點擊 → 通俗解釋",
    "miActual": "實際",
    "miEstimate": "預期",
    "miCascadeExpand": "查看連鎖影響",
    "miCascadeCollapse": "收起連鎖影響",
    "miLaymanExpand": "查看解釋",
    "miLaymanCollapse": "收起解釋",
    "miReleaseDate": "發布日",
    "miNextRelease": "下次發布",
    "miCascadeTitle": "此次發布對市場的連鎖影響",
    "miMagStrong": "強",
    "miMagMedium": "中",
    "miMagWeak": "弱",
    "miNoCascade": "符合預期的結果 — 市場已提前消化，預計不會出現大幅波動。",
    "lbWhat": "這個指標是什麼？",
    "lbWhy": "為什麼重要？",
}

def main():
    errors = 0
    for lang_file in sorted(ROOT.glob("*.json")):
        lang = lang_file.stem
        with open(lang_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        if "macro" in data:
            print(f"[SKIP] {lang}: macro namespace already exists")
            continue

        # Pick translations for this language
        if lang in TRANSLATIONS:
            keys = dict(TRANSLATIONS[lang])
        elif lang == "zh-TW":
            # Use zh-TW overrides for short keys, en for LAYMAN content
            keys = dict(TRANSLATIONS["en"])  # fallback
            keys.update(ZH_TW_OVERRIDES)
            # Use zh-CN LAYMAN content (simplified→traditional approximation)
            for k in TRANSLATIONS["zh-CN"]:
                if k.startswith("l") and k[1].isupper():
                    keys[k] = TRANSLATIONS["zh-CN"][k]
        else:
            # Fallback: use English for all keys
            keys = dict(TRANSLATIONS["en"])

        data["macro"] = keys

        with open(lang_file, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")

        print(f"[OK]   {lang}: added {len(keys)} keys to macro namespace")

    return errors

if __name__ == "__main__":
    sys.exit(main())
