import { Shield } from 'lucide-react';
import { generateSeoMetadata } from '@/lib/seo';
import { getTranslations } from 'next-intl/server';
import type { Metadata } from 'next';

export async function generateMetadata({
  params,
}: {
  params: { locale: string };
}): Promise<Metadata> {
  const t = await getTranslations({ locale: params.locale, namespace: 'seo' });
  return generateSeoMetadata({
    title: `Privacy Policy - ${t('homeTitle')}`,
    description: t('homeDescription'),
    path: '/privacy',
    locale: params.locale,
  });
}

export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-12">
      {/* Header */}
      <div className="text-center mb-12">
        <div className="w-14 h-14 rounded-xl bg-cf-primary/10 flex items-center justify-center mx-auto mb-4">
          <Shield className="w-7 h-7 text-cf-primary" />
        </div>
        <h1 className="text-4xl font-heading font-bold text-cf-text-primary mb-4">
          Privacy Policy
        </h1>
        <p className="text-sm text-cf-text-secondary">
          Last updated: April 1, 2026
        </p>
      </div>

      <div className="cf-card p-8 space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-cf-text-secondary leading-relaxed">
            Flowvium (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is operated by THE ELIOT K FINANCIAL. This Privacy Policy
            explains how we collect, use, disclose, and safeguard your information when you visit our
            website at https://flowvium.net (the &quot;Site&quot;) and use our supply chain
            intelligence platform (the &quot;Service&quot;). Please read this Privacy Policy carefully. By
            accessing or using the Site and Service, you acknowledge that you have read, understood,
            and agree to be bound by the terms of this Privacy Policy. If you do not agree with the
            terms of this Privacy Policy, please do not access the Site or use the Service.
          </p>
        </section>

        {/* Information We Collect */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            1. Information We Collect
          </h2>
          <div className="space-y-4 text-cf-text-secondary leading-relaxed">
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">1.1 Information You Provide Voluntarily</h3>
              <p>
                When you contact us via email, submit feedback through our feedback widget, or
                communicate with us in any other manner, you may voluntarily provide us with personal
                information such as your name, email address, and the content of your message. We only
                collect personal information that you choose to share with us. Using Flowvium does not
                require creating an account or providing any personal information. The feedback widget
                on our Site uses a mailto: link to open your default email client, meaning your
                feedback is sent directly through your own email service and is not processed through
                our servers.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">1.2 Information Collected Automatically</h3>
              <p>
                When you visit the Site, we may automatically collect certain information about your
                device and your visit. This information may include your Internet Protocol (IP) address,
                browser type, operating system, referring URLs, pages viewed, links clicked, access
                times and dates, and other browsing behavior data. This information is collected through
                cookies, web beacons, log files, and similar tracking technologies. We use this data in
                aggregate form to understand how our users interact with the Site, improve the user
                experience, and monitor overall site performance. We do not use this automatically
                collected data to personally identify individual visitors unless required by law.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">1.3 Analytics Data</h3>
              <p>
                We may use third-party analytics services, such as Google Analytics, to help us
                understand how users interact with our Site. These services may collect information
                about your use of the Site, including pages visited, time spent on pages, navigation
                paths, and technical information about your device and browser. Google Analytics uses
                cookies and similar technologies to collect and analyze this data. The information
                generated by these cookies is transmitted to and stored by Google on servers in the
                United States. Google may use this information to evaluate your use of the website,
                compile reports on website activity, and provide other services relating to website
                activity and internet usage. For more information on how Google processes your data,
                please review Google&apos;s Privacy Policy at https://policies.google.com/privacy.
              </p>
            </div>
          </div>
        </section>

        {/* Cookie Usage */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            2. Cookie Usage
          </h2>
          <div className="space-y-4 text-cf-text-secondary leading-relaxed">
            <p>
              Cookies are small text files placed on your device by websites you visit. They are widely
              used to make websites work efficiently, provide information to site owners, and enable
              certain features. Flowvium uses the following types of cookies:
            </p>
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">2.1 Essential Cookies</h3>
              <p>
                These cookies are necessary for the Site to function properly. They enable core
                functionality such as language preferences, session management, and security features.
                Without these cookies, certain parts of the Site may not function correctly. These
                cookies do not collect personal information and cannot be disabled without affecting
                site functionality.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">2.2 Analytics Cookies</h3>
              <p>
                We use analytics cookies (such as those set by Google Analytics) to collect aggregate
                information about how visitors use the Site. This helps us understand which pages are
                most popular, how visitors navigate between pages, and where users encounter errors.
                All data collected by analytics cookies is aggregated and anonymous. We use this
                information solely to improve how the Site works and the quality of our Service.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-cf-text-primary mb-2">2.3 Advertising Cookies</h3>
              <p>
                We may use third-party advertising services, such as Google AdSense, which may place
                cookies on your device to serve relevant advertisements based on your browsing behavior
                across the internet. Google AdSense uses cookies to serve ads based on your prior visits
                to our Site and other websites. Google&apos;s use of advertising cookies enables it and its
                partners to serve ads based on your visit to our Site and other sites on the internet.
                You may opt out of personalized advertising by visiting Google&apos;s Ads Settings at
                https://adssettings.google.com or the Network Advertising Initiative opt-out page at
                https://optout.networkadvertising.org. You may also configure your browser to reject
                cookies or alert you when cookies are being sent. Please note that disabling cookies may
                limit your ability to use certain features of the Site.
              </p>
            </div>
          </div>
        </section>

        {/* Third-Party Services */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            3. Third-Party Services
          </h2>
          <div className="space-y-4 text-cf-text-secondary leading-relaxed">
            <p>
              Our Site may contain links to third-party websites, services, or content that are not
              owned or controlled by Flowvium. We have no control over, and assume no responsibility
              for, the content, privacy policies, or practices of any third-party websites or services.
              We use the following third-party services in connection with the Site:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Vercel:</strong> Our Site is hosted on Vercel. Vercel may collect certain
                technical data in connection with hosting the Site. Vercel&apos;s privacy policy is
                available at https://vercel.com/legal/privacy-policy.
              </li>
              <li>
                <strong>Google Analytics:</strong> We use Google Analytics to collect and analyze usage
                data. Google&apos;s privacy policy is available at https://policies.google.com/privacy.
              </li>
              <li>
                <strong>Google AdSense:</strong> We may display advertisements served by Google AdSense.
                Google&apos;s advertising privacy policy is available at https://policies.google.com/technologies/ads.
              </li>
            </ul>
            <p>
              We encourage you to review the privacy policies of any third-party services you interact
              with through our Site. We are not responsible for the privacy practices of third parties.
            </p>
          </div>
        </section>

        {/* How We Use Your Information */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            4. How We Use Your Information
          </h2>
          <div className="text-cf-text-secondary leading-relaxed">
            <p className="mb-3">We may use the information we collect for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To operate, maintain, and improve the Site and Service</li>
              <li>To respond to your inquiries, feedback, and support requests</li>
              <li>To monitor and analyze usage trends and user behavior in aggregate</li>
              <li>To detect, prevent, and address technical issues and security vulnerabilities</li>
              <li>To comply with applicable laws, regulations, and legal processes</li>
              <li>To display relevant advertisements through third-party ad networks</li>
              <li>To communicate with you about updates, features, or changes to the Service</li>
            </ul>
          </div>
        </section>

        {/* Data Security */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            5. Data Security
          </h2>
          <p className="text-cf-text-secondary leading-relaxed">
            We implement reasonable administrative, technical, and physical security measures to
            protect the information we collect and maintain. Our Site is served over HTTPS, ensuring
            that data transmitted between your browser and our servers is encrypted. However, no
            method of transmission over the Internet or method of electronic storage is completely
            secure. While we strive to use commercially acceptable means to protect your information,
            we cannot guarantee its absolute security. We are not responsible for the circumvention
            of any privacy settings or security measures contained on the Site. In the event of a
            data breach that affects your personal information, we will notify you in accordance
            with applicable law.
          </p>
        </section>

        {/* User Rights */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            6. User Rights
          </h2>
          <div className="space-y-4 text-cf-text-secondary leading-relaxed">
            <p>
              Depending on your jurisdiction, you may have certain rights regarding your personal
              information. These rights may include:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Right to Access:</strong> You may request a copy of the personal information
                we hold about you.
              </li>
              <li>
                <strong>Right to Rectification:</strong> You may request that we correct any
                inaccurate or incomplete personal information.
              </li>
              <li>
                <strong>Right to Erasure:</strong> You may request that we delete your personal
                information, subject to certain exceptions provided by law.
              </li>
              <li>
                <strong>Right to Restrict Processing:</strong> You may request that we limit the
                processing of your personal information under certain circumstances.
              </li>
              <li>
                <strong>Right to Data Portability:</strong> You may request that we provide your
                personal information in a structured, commonly used, and machine-readable format.
              </li>
              <li>
                <strong>Right to Opt-Out:</strong> You may opt out of personalized advertising and
                analytics tracking as described in the Cookie Usage section above.
              </li>
            </ul>
            <p>
              To exercise any of these rights, please contact us at taeshinkim11@gmail.com. We will
              respond to your request within a reasonable timeframe and in accordance with applicable
              law. We may need to verify your identity before fulfilling your request.
            </p>
          </div>
        </section>

        {/* Children's Privacy */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            7. Children&apos;s Privacy
          </h2>
          <p className="text-cf-text-secondary leading-relaxed">
            Flowvium is not directed to individuals under the age of 13 (or the applicable age of
            digital consent in your jurisdiction). We do not knowingly collect personal information
            from children under 13. If we become aware that we have inadvertently collected personal
            information from a child under 13, we will take steps to delete such information as soon
            as possible. If you are a parent or guardian and believe that your child has provided us
            with personal information, please contact us at taeshinkim11@gmail.com so that we can
            take appropriate action.
          </p>
        </section>

        {/* Data Retention */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            8. Data Retention
          </h2>
          <p className="text-cf-text-secondary leading-relaxed">
            We retain automatically collected data (such as analytics and log data) for a reasonable
            period necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer
            retention period is required or permitted by law. Personal information provided through
            feedback or email correspondence is retained only for as long as necessary to address your
            inquiry or for our legitimate business purposes. You may request deletion of your personal
            information at any time by contacting us.
          </p>
        </section>

        {/* International Data Transfers */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            9. International Data Transfers
          </h2>
          <p className="text-cf-text-secondary leading-relaxed">
            Flowvium is operated from the United States and our Site is hosted on servers located
            in various regions. If you are accessing the Site from outside the United States, please
            be aware that your information may be transferred to, stored, and processed in the United
            States or other countries where our service providers maintain facilities. By using the
            Site, you consent to the transfer of your information to countries outside of your country
            of residence, which may have different data protection rules than those of your country.
          </p>
        </section>

        {/* Changes to This Policy */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            10. Changes to This Privacy Policy
          </h2>
          <p className="text-cf-text-secondary leading-relaxed">
            We reserve the right to update or modify this Privacy Policy at any time without prior
            notice. Any changes will be effective immediately upon posting the revised Privacy Policy
            on the Site. The &quot;Last updated&quot; date at the top of this Privacy Policy indicates when
            the policy was last revised. Your continued use of the Site and Service after any changes
            to this Privacy Policy constitutes your acceptance of the revised policy. We encourage
            you to review this Privacy Policy periodically to stay informed about how we collect,
            use, and protect your information.
          </p>
        </section>

        {/* Contact */}
        <section>
          <h2 className="text-xl font-heading font-bold text-cf-text-primary mb-4">
            11. Contact Us
          </h2>
          <div className="text-cf-text-secondary leading-relaxed">
            <p className="mb-3">
              If you have any questions, concerns, or requests regarding this Privacy Policy or our
              data practices, please contact us at:
            </p>
            <div className="bg-cf-background rounded-lg p-4">
              <p className="font-medium text-cf-text-primary">THE ELIOT K FINANCIAL — Flowvium</p>
              <p>Email: <a href="mailto:taeshinkim11@gmail.com" className="text-cf-primary hover:underline">taeshinkim11@gmail.com</a></p>
              <p>Website: <a href="https://flowvium.net" className="text-cf-primary hover:underline">https://flowvium.net</a></p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
